### ISSUE TITLE
cue get go: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by florianl** [cue-lang/cue#2715] opened 2023-11-30 09:23 UTC
### What version of CUE are you using (`cue version`)?

<pre>
 $ cue version
 cue version v0.6.0
 go version go1.21.4
       -buildmode exe
        -compiler gc
   DefaultGODEBUG panicnil=1
      CGO_ENABLED 1
           GOARCH amd64
             GOOS linux
          GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes. Also reproducable with [current head](https://github.com/cue-lang/cue/commit/141925a62c4b579ff6e7399f5948da4935fddb94) of `master`.

<pre>
$ cue version
 cue version v0.6.1-0.20231130085212-141925a62c4b
 go version go1.21.4
       -buildmode exe
        -compiler gc
   DefaultGODEBUG panicnil=1
      CGO_ENABLED 1
           GOARCH amd64
             GOOS linux
          GOAMD64 v1
</pre>

### What did you do?

<pre>
$ cue get go github.com/elastic/go-elasticsearch/v8
 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
     panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbc1d05]
 goroutine 1 [running]:
 [cuelang.org/go/cmd/cue/cmd.recoverError(0xc02ed87e78)](http://cuelang.org/go/cmd/cue/cmd.recoverError(0xc02ed87e78))
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/root.go:318 +0x76
 panic({0xc87e00?, 0x13ec140?})
     /usr/local/go/src/runtime/panic.go:914 +0x21f
 [cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40](http://cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40), {0xc00003c044, 0x10}, 0x0)
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/get_go.go:437 +0x65
 [cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40](http://cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40), {0xc00003c044, 0x10}, 0xc0002b9800)
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/get_go.go:553 +0xafa
 [cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40](http://cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40), {0xc00003c044, 0x10}, 0xc0002d5980)
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/get_go.go:553 +0xafa
 [cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40](http://cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0193b9d40), {0xc00003c044, 0x10}, 0xc000aecc00)
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/get_go.go:553 +0xafa
 [cuelang.org/go/cmd/cue/cmd.extract(0xc0004007b0](http://cuelang.org/go/cmd/cue/cmd.extract(0xc0004007b0), {0xc0003eed20, 0x1, 0x1})
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/get_go.go:416 +0x3b8
 [cuelang.org/go/cmd/cue/cmd.newGoCmd.mkRunE.func1(0xc00040c400](http://cuelang.org/go/cmd/cue/cmd.newGoCmd.mkRunE.func1(0xc00040c400)?, {0xc0003eed20, 0x1, 0x1})
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/root.go:87 +0xab
 [github.com/spf13/cobra.(*Command).execute(0xc000414c00](http://github.com/spf13/cobra.(*Command).execute(0xc000414c00), {0xc0003eece0, 0x1, 0x1})
     /home/flehner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
 [github.com/spf13/cobra.(*Command).ExecuteC(0xc000330f00)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc000330f00))
     /home/flehner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
 [github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
     /home/flehner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
 [cuelang.org/go/cmd/cue/cmd.(*Command).Run](http://cuelang.org/go/cmd/cue/cmd.(*Command).Run)(0xc0004007b0, {0x3?, 0x3?})
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/root.go:303 +0x65
 [cuelang.org/go/cmd/cue/cmd.Main()](http://cuelang.org/go/cmd/cue/cmd.Main())
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/cmd/root.go:231 +0x72
 main.main()
     /home/flehner/go/pkg/mod/cuelang.org/go@v0.6.0/cmd/cue/main.go:24 +0x13
</pre>

### What did you expect to see?

Download the CUE definitions for github.com/elastic/go-elasticsearch/v8.

### What did you see instead?

`panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by mvdan** [comment] 2023-12-01 12:08
This appears to be a duplicate of https://github.com/cue-lang/cue/issues/2046 :) Closing this one since that one already has quite a bit of a discussion going on.

**Closed as not planned by mvdan** 2023-12-01 12:08 UTC
Labels: NeedsInvestigation, Triage
