### ISSUE TITLE
cue fmt changed well formated code

### ISSUE THREAD

**Issue by nxcc** [cue-lang/cue#2725] opened 2023-12-05 13:36 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.7.0-rc.1
</pre>

### Does this issue reproduce with the latest stable release?
no

### What did you do?

<pre>
exec cat fmt.cue
cmp stdout fmt.cue

exec cue fmt fmt.cue
cmp stdout fmt.cue

-- fmt.cue --
a: {
	b: ""
	c: *{} | {d: string}
}
</pre>

### What did you expect to see?
PASS

### What did you see instead?
FAIL: ... stdout and fmt.cue differ

spoiler: formated output is
<pre>
a: {
	b:           ""
	c: *{} | {d: string}
}
</pre>

**Comment by PierreR** [comment] 2024-01-11 16:07
Same  issue with arrays:
```
aaa: string
b:   string
c:   [...string]
```
will be reformatted as
```
aaa: string
b:   string
c: [...string]
```

using version:
```
cue version v0.7.0

go version go1.21.5
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
```

**Comment by NoamTD** [comment] 2024-04-21 07:06
looks like this is a duplicate of [#3015](https://cuelang.org/issue/3015)

**Comment by myitcv** [comment] 2024-04-23 05:26
Agreed, thanks @NoamTD

**Closed as completed by myitcv** 2024-04-23 05:26 UTC
Labels: NeedsFix, fmt
