### ISSUE TITLE
cue flow doesn't recognize dependencies from imported packages

### ISSUE THREAD

**Issue by sourcec0de** [cue-lang/cue#1615] opened 2022-04-03 05:56 UTC
### Preface
🙇  first of all, thank you for all the tremendous work everyone has put into cue. 

### Overview

I'm in the process of evaluating cue's flow package for a task running system similar to cue tools.
Something I found myself reaching for is importing references from another file.

I've attempted to implement this using the Go API but it doesn't seem like flow is able to load tasks imported from packages.

This example is a minimal reproduction of what I'm trying to achieve but using `cue cmd` instead of the Go flow API.
I'm wondering if this group has any thoughts.
If this is desirable I would love to contribute a PR.

This example makes a bit more sense when packages live in different folders.

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3-beta.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Attempted to import commands from another file.

```
.
├── cue.mod
│   └── module.cue
├── build_tool.cue
└── deploy_tool.cue

1 directory, 3 files

```

`cue.mod/module.cue`
```cue
module: "playground.sh"
```

`build_tool.cue`
```cue
package build

import (
	"tool/exec"
	"tool/cli"
)

command: build: {
	cowsay: exec.Run & {
		cmd:    "cowsay moo"
		stdout: string
	}

	echo: cli.Print & {
		text: cowsay.stdout
	}
}
```

`deploy_tool.cue`
```cue
package deploy

import (
	"tool/cli"
	"playground.sh:build"
)

command: deploy: {
	print: cli.Print & {
		text: build.command.build.cowsay.stdout
	}
}
```

```sh
cue cmd deploy deploy_tool.cue
```

### What did you expect to see?
```
$ cue cmd deploy deploy_tool.cue
 _____ 
< moo >
 ----- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

```

### What did you see instead?
```
$ cue cmd deploy deploy_tool.cue
command.deploy.print.text: invalid string argument: non-concrete value string:
    ./deploy_tool.cue:9:2
    ./deploy_tool.cue:10:3
    tool/cli:4:3
    tool/cli:4:9
```

**Comment by sourcec0de** [comment] 2022-04-03 21:03
Looks like this is explicitly disallowed when attempting to find implied tasks.
https://github.com/cue-lang/cue/blob/41364815392be45549d4be05195010a183b4ac04/tools/flow/tasks.go#L165-L170

Was this skipped because there's a bug that causes package imports to not work?

**Comment by verdverm** [comment] 2022-04-04 16:19
You can actually import task definitions if you avoid the `_tool.cue` suffix and the `tool/*` imports. You have to manually ensure the `$id` field and others (depending on task) are present and correct.

There are however some tricky semantics around dependencies (#1595, #1088 ). These also manifest through imports. The key is to get all the tasks referenced within the Value cue/flow will process, and then make sure you get your deps setup correctly.

Also note, an overhaul of `cue cmd` is planned, at which point it will become `cue run`. (related issues exist,  #?)

**Comment by rogpeppe** [comment] 2022-04-19 16:29
@sourcec0de Thanks for the report.

If you want commands to be considered, they have to be explicitly included in the root package's _tool.cue files.

Here's one way this example could do that, as a testscript example:

```
exec cue cmd deploy deploy_tool.cue

-- cue.mod/module.cue --

module: "playground.sh"

-- build_tool.cue --

package build

import (
	"tool/exec"
	"tool/cli"
)

command: build: {
	cowsay: exec.Run & {
		cmd:    "cowsay moo"
		stdout: string
	}

	echo: cli.Print & {
		text: cowsay.stdout
	}
}

-- deploy_tool.cue --

package deploy

import (
	"tool/cli"
	"playground.sh:build"
)


command: deploy: {
	print: cli.Print & command.build & {
		cowsay: _
		text: cowsay.stdout
	}
}
// Include the external commands.
command: build.command
```

ISTM that this is working as intended, so I'll close it as such for now. Please comment or re-open if you think that's wrong.

**Closed as completed by rogpeppe** 2022-04-19 16:29 UTC
Labels: WorkingAsIntended

**Comment by verdverm** [comment] 2022-04-20 18:59
I think the idea was that this is more of a feature-request than a bug report. I know I wrote an example that showed two examples (same package & imported) where one might expect to have the task inferred across package boundaries like it does within a package.
