### ISSUE TITLE
cue imports within cue.mod pkg directory

### ISSUE THREAD

**Issue by kghenderson** [cue-lang/cue#2465] opened 2023-06-28 12:19 UTC
### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.6.0-alpha.2

go version go1.20.5
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?

- I have within the cue.mod/pkg/my.domain/x/... directories.  
- I have a mydef1 and mydef2 packages defined in there as parallel directories.
- mydef2 imports mydef1 using `import "my.domain/x/mydef1`
- when I `cue vet` from within the mydef2 directory, I get a 'cannot find package` error (same for cue def & export)
- I also have a data directory outside of cue.mod
- when i import mydef2, vet & cue commands works and mydef1 is correctly imported and works as expected
 
```
project_root
    cue.mod/pkg/my.domain/x/mydef1:
    cue.mod/pkg/my.domain/x/mydef2:
         import "my.domain/x/mydef1"
         > vet/def/export commands fail, cannot find mydef1
    data/myfile1:
        import "my.domain/x/mydef2"
        > vet/def/export commands work as expected
```

### What did you expect to see?

vet/def/export working successfully within mydef2 directory for validating this schema.

### What did you see instead?

import error, and still works successfully outside of cue.mod directory.

**Comment by kghenderson** [comment] 2023-06-28 12:25
As it stands, the ability to vet directly within the cue.mod packages is too important to me to give up, so even though it's working outside of here, I'm choosing to duplicate the def1 code in the packages over using the import until this is eventually resolved. Note that there a are dozens of small packages here, and this is just a trivial example to illustrate the concept.

**Comment by rogpeppe** [comment] 2023-06-29 10:20
I tried to write a reproducer for this and failed. This testscript succeeds, but by your description I think it should fail. Perhaps you could adapt it to show your issue?

```
exec cue export .
cmp stdout want-stdout.json
cd $WORK/cue.mod/pkg/my.domain/x/mydef1
exec cue vet .
cd $WORK/cue.mod/pkg/my.domain/x/mydef2
exec cue vet .

-- want-stdout.json --
{
    "z": 1
}
-- cue.mod/module.cue --
module: "example.com"
-- main.cue --
package main
import "my.domain/x/mydef2"
z: mydef2.y

-- cue.mod/pkg/my.domain/x/cue.mod/module.cue --
module: "my.domain/x"
-- cue.mod/pkg/my.domain/x/mydef1/d.cue --
package mydef1
x: 1
-- cue.mod/pkg/my.domain/x/mydef2/d.cue --
package mydef2

import "my.domain/x/mydef1"

y: mydef1.x
```

**Comment by myitcv** [comment] 2023-07-11 16:57
Also noting that `cue vet my.domain/x/mydef1` and `cue vet my.domain/x/mydef2` work from the root of that example. i.e. you do not need to change directories to vet those packages.

**Comment by myitcv** [comment] 2023-07-11 16:59
Grr hit `Cmd+Enter` instead of `Enter`:

```
exec cue export .
cmp stdout want-stdout.json
exec cue vet my.domain/x/mydef1
exec cue vet my.domain/x/mydef2

-- want-stdout.json --
{
    "z": 1
}
-- cue.mod/module.cue --
module: "example.com"
-- main.cue --
package main
import "my.domain/x/mydef2"
z: mydef2.y

-- cue.mod/pkg/my.domain/x/cue.mod/module.cue --
module: "my.domain/x"
-- cue.mod/pkg/my.domain/x/mydef1/d.cue --
package mydef1
x: 1
-- cue.mod/pkg/my.domain/x/mydef2/d.cue --
package mydef2

import "my.domain/x/mydef1"

y: mydef1.x
```

The above passes as expected.

**Comment by myitcv** [comment] 2023-07-11 17:05
Noting however the current bug with respect to `/...` wildcards show in https://github.com/cue-lang/cue/issues/2484.

**Comment by mvdan** [comment] 2024-05-21 09:38
This issue has been in a "cannot reproduce" state for eleven months now, so I think we should close it for the time being. I am more than happy to reopen it if @kghenderson responds to the questions above or with a specific reproducer, of course.

**Closed as not planned by mvdan** 2024-05-21 09:38 UTC
Labels: CannotReproduce, NeedsInvestigation
