### ISSUE TITLE
segmentation violation on `cue get go net/http`

### ISSUE THREAD

**Issue by yujunz** [cue-lang/cue#2479] opened 2023-07-11 08:47 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.6.0-alpha.2.0.20230710213742-fa6e229ee207
</pre>

### Does this issue reproduce with the latest stable release?

Yes. Same error on v0.4.3

### What did you do?

```
go run cuelang.org/go/cmd/cue@master get go net/http
```

### What did you expect to see?

Generate cue from go modules

### What did you see instead?

```
go: downloading cuelang.org/go v0.6.0-alpha.2.0.20230710213742-fa6e229ee207
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17eda79]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00c0dfeb8)
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/cmd/root.go:315 +0x7b
panic({0x18b5440, 0x1fec810})
	/usr/local/Cellar/go/1.20.4/libexec/src/runtime/panic.go:884 +0x213
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0130a6480, {0xc00003e004, 0x36}, 0x0)
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/cmd/get_go.go:437 +0x79
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0130a6480, {0xc00003e004, 0x36}, 0xc0003f8000)
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/cmd/get_go.go:553 +0xb1a
cuelang.org/go/cmd/cue/cmd.extract(0xc00027bb00, {0xc00029acf0, 0x1, 0x1})
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/cmd/get_go.go:416 +0x3e5
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0002e4c00?, {0xc00029acf0, 0x1, 0x1})
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/cmd/root.go:87 +0xb3
github.com/spf13/cobra.(*Command).execute(0xc0002e4c00, {0xc00029acb0, 0x1, 0x1})
	/Users/yujunz/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000266f00)
	/Users/yujunz/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yujunz/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00027bb00, {0x3?, 0x3?})
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/cmd/root.go:300 +0x6b
cuelang.org/go/cmd/cue/cmd.Main()
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/cmd/root.go:228 +0x79
main.main()
	/Users/yujunz/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.2.0.20230710213742-fa6e229ee207/cmd/cue/main.go:24 +0x19
exit status 2
```

**Comment by myitcv** [comment] 2023-07-11 09:21
This is likely a duplicate of the underlying issue in #668.

**Closed as completed by myitcv** 2023-07-11 09:21 UTC
Labels: NeedsInvestigation
