### ISSUE TITLE
cmd/cue: cannot export when definitions contain required fields

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2370] opened 2023-04-28 20:30 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230428121230-80d6ea032057

go version devel go1.21-3ed8a1e629 Tue Mar 28 05:41:44 2023 +0000
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 80d6ea032057b40e405eefab6015e92bbc5cc2a5
        vcs.time 2023-04-28T12:12:30Z
    vcs.modified false

</pre>

### What did you do?

```
exec cue export x.cue

-- x.cue --
#X: a!: int
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> exec cue export x.cue
[stderr]
#X.a: field is required but not present
[exit status 1]
```

**Comment by mvdan** [comment] 2023-04-28 20:33
Seems like a duplicate of https://github.com/cue-lang/cue/issues/2336 :)

**Closed as not planned by mvdan** 2023-04-28 20:33 UTC
Labels: NeedsFix
