### ISSUE TITLE
How to hidden fields in FillPath function

### ISSUE THREAD

**Issue by inksnw** [cue-lang/cue#2093] opened 2022-11-14 10:04 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.4.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
```go
package main

import (
	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"fmt"
)

func main() {
	data := `{ "apiVersion": "v1",	"another": 123 }`
	cueTmpl := `obj: { apiVersion: string }`
	cueValue := cuecontext.New().CompileBytes([]byte(cueTmpl))
	jsonData := cueValue.Context().CompileString(data)
	cueValue = cueValue.FillPath(cue.ParsePath("obj"), jsonData)
	b, _ := cueValue.LookupPath(cue.ParsePath("obj")).MarshalJSON()
	fmt.Printf("%s", string(b))
}

```
I want to use `kubectl get deploy -o json` as input to render json data via cue file, then generate yaml for edit by front-end, but some key can't be edit like metadata.creationTimestamp, so i want remove it from result, may have a optional flag?

### What did you expect to see?
```json
{"apiVersion":"v1"}
```

### What did you see instead?
```json
{"apiVersion":"v1","another":123}
```

**Comment by rogpeppe** [comment] 2022-11-14 14:29
@inksnw Thanks for the report, but this seems like it's working as intended. Please feel free to open a discussion if you want to ask a question about how to do something. Closing accordingly.

**Closed as completed by rogpeppe** 2022-11-14 14:29 UTC
Labels: WorkingAsIntended
