### ISSUE TITLE
cue/cmd: unclear error when no package statement

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1500] opened 2022-01-30 04:57 UTC
### What version of CUE are you using (`cue version`)?

<pre>
0.4.1
</pre>

### What did you do?

```cue
exec cue cmd say

-- in_tool.cue --
import "tool/exec"

command: {
  say: do: exec.Run & {
    cmd: ["echo", "hello world"]
  }
}
```

I'm not sure what the output should be

It says:

```
$ cue cmd say
could not create command definitions: non-concrete value _
```

**Comment by rogpeppe** [comment] 2022-04-19 12:22
I can't reproduce this - perhaps the issue has been fixed.
I get the following output:

```
cmd must be run as one of its subcommands: unknown subcommand "say"
Ensure commands are defined in a "_tool.cue" file.
Run 'cue help cmd' for known subcommands.
```

which isn't nearly so cryptic. I'll close this issue accordingly - please reopen if it still seems to be a problem.

**Closed as completed by rogpeppe** 2022-04-19 12:22 UTC
Labels: CannotReproduce
