### ISSUE TITLE
mod/modfile: split syntax into its own data structure

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3220] opened 2024-06-12 12:55 UTC
Currently the `modfile.File` type is used directly to marshal and unmarshal the module.cue
contents. However in the future we want to be able to preserve comments and other formatting
that cannot be expressed in the Go data structure. The [Go modfile package](https://pkg.go.dev/golang.org/x/mod/modfile#File) splits
the syntax from the parsed result and we should probably do the same for the CUE one.

**Comment by mvdan** [comment] 2024-08-08 12:58
Appears to be a duplicate of https://github.com/cue-lang/cue/issues/2898, please remember to search :)

**Closed as not planned by mvdan** 2024-08-08 12:58 UTC
Labels: NeedsFix, modules
