### ISSUE TITLE
unity: add cue/stats info to Unity output

### ISSUE THREAD

**Issue by mpvl** [cue-lang/cue#1946] opened 2022-09-20 12:03 UTC
**Is your feature request related to a problem? Please describe.**
The execution time difference currently displayed in Unity seem a bit unreliable.

**Describe the solution you'd like**
I would like Unity to use cue/stats metrics to get more detailed and accurate performance metrics between implementations.

Note that accessing these stats is mostly still internal, but could probably be exposed as a command line tool flag.

**Describe alternatives you've considered**
Using running time, which seems inaccurate.

**Additional context**
See cue/stats package.

**Comment by mvdan** [comment] 2022-09-22 09:03
Closing as a duplicate of https://github.com/cue-unity/unity/issues/37 per @myitcv. Also a reminder that Unity has its own issue tracker :)

**Closed as not planned by mvdan** 2022-09-22 09:03 UTC
Labels: FeatureRequest
