### ISSUE TITLE
cmd/cue: inconsistent vet behavior if using identifier from package or not

### ISSUE THREAD

**Issue by davidovich** [cue-lang/cue#3616] opened 2024-12-05 02:09 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version

go version go1.23.2
      -buildmode exe
       -compiler gc
  DefaultGODEBUG asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
         GOARM64 v8.0
cue.lang.version v0.11.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

I use a package which contains a struct to deduce filenames from an input. Validate passes when it should not.
Copying the same code (from the package) on the main cue file makes the validation fail - as expected.

I created a repro repository: https://github.com/davidovich/cue-bug 

You can clone and issue this cue command:

```bash
git checkout correctly-fails
cue export --with-context -l '_input:' -l 'filename' failure/config.cue failure/data.yaml
```

With the above tag checked out, which has the package code in the config.cue file, validation fails, as expected.

```bash
git checkout use-imported-package
cue export --with-context -l '_input:' -l 'filename' failure/config.cue failure/data.yaml
```

With the `use-imported-package` tag checked out, export succeeds, hence no validation error.

### What did you expect to see?

Using or not an identifier in a package should not change the validation outcome.

### What did you see instead?

When using an identifier in a package, validation passes.

**Comment by myitcv** [comment] 2024-12-05 13:17
@davidovich thanks for the report. I am, however, struggling to reproduce what you see above:

```
++ mktemp -d
+ cd /tmp/tmp.XjJPFxnSlF
+ git clone --quiet https://github.com/davidovich/cue-bug
+ cd cue-bug
+ git checkout correctly-fails
HEAD is now at 8604cbb demo bug when using identifiers from library
+ cue export --with-context -l _input: -l filename failure/config.cue failure/data.yaml
notAllowed: field not allowed:
    ./failure/data.yaml:4:3
+ git checkout use-imported-package
Previous HEAD position was 8604cbb demo bug when using identifiers from library
HEAD is now at b0cd6f7 should fail but does not
+ cue export --with-context -l _input: -l filename failure/config.cue failure/data.yaml
notAllowed: field not allowed:
    ./failure/data.yaml:4:3
```

The script I ran for the above hopefully follows your repro steps faithfully:

```
set -x

cd $(mktemp -d)
git clone --quiet https://github.com/davidovich/cue-bug
cd cue-bug

git checkout correctly-fails
cue export --with-context -l '_input:' -l 'filename' failure/config.cue failure/data.yaml

git checkout use-imported-package
cue export --with-context -l '_input:' -l 'filename' failure/config.cue failure/data.yaml
```

**Comment by davidovich** [comment] 2024-12-05 14:10
@myitcv thanks for testing my repro. I just ran your steps just to be doubly sure, and exports succeeds where it shouldn't. 

```
cue export --with-context -l '_input:' -l 'filename' failure/config.cue failure/data.yaml
{
    "Name": "/var/folders/rp/57wxsc316sv5669807thfjx80000gp/T/tmp.Zup5ANJRSJ/cue-bug/failure/data.yaml",
    "aField": true,
    "bField": "value",
    "notAllowed": true
}
```

Are there some environmental inputs which could make a difference?

**Comment by myitcv** [comment] 2024-12-05 14:51
How very strange. Please can you confirm exactly what CUE version you are using? The details above appear to be missing the crucial first line!

> Are there some environmental inputs which could make a difference?

Possibly, but let's confirm we are testing using the same version first.

**Comment by myitcv** [comment] 2024-12-05 14:55
Ah, I can now reproduce using both v0.11.0 and current tip:

```
++ mktemp -d
+ cd /tmp/tmp.0YyQPn8fYm
+ git clone --quiet https://github.com/davidovich/cue-bug
+ cd cue-bug
+ git checkout correctly-fails
HEAD is now at 8604cbb demo bug when using identifiers from library
+ cue export --with-context -l _input: -l filename failure/config.cue failure/data.yaml
notAllowed: field not allowed:
    ./failure/config.cue:1:1
    ./failure/config.cue:17:20
    ./failure/config.cue:18:2
    ./failure/config.cue:18:32
    ./failure/config.cue:19:3
    ./failure/config.cue:21:7
    ./failure/config.cue:24:14
    ./failure/config.cue:24:30
    ./failure/config.cue:28:10
    ./failure/config.cue:34:1
    ./failure/config.cue:34:15
    ./failure/data.yaml:4:3
+ git checkout use-imported-package
Previous HEAD position was 8604cbb demo bug when using identifiers from library
HEAD is now at b0cd6f7 should fail but does not
+ cue export --with-context -l _input: -l filename failure/config.cue failure/data.yaml
{
    "Name": "/tmp/tmp.0YyQPn8fYm/cue-bug/failure/data.yaml",
    "aField": true,
    "bField": "value",
    "notAllowed": true
}
```

I had failed to recall that I set `CUE_EXPERIMENT=evalv3` locally. This is in order to help try out the new version of the evaluator.

What that tells me however is that the bug you are seeing here exists in the current default "old" evaluator, but is _fixed_ in the new evaluator, which is active when `CUE_EXPERIMENT=evalv3`

Perhaps you could try setting that environment variable to help confirm?

**Comment by davidovich** [comment] 2024-12-05 15:01
I confirm. Setting `CUE_EXPERIMENT=evalv3` fixes the problem and exposes intended behavior.

**Comment by myitcv** [comment] 2024-12-05 16:02
Thanks for confirming. Whilst `evalv3` behaves as you expect here, I'm not actually sure that it is doing "the right thing", because of the following embedding:

```
_parameters & #schema
```

I'm seeking to unravel things a bit here and then get Marcel to opine.

**Comment by myitcv** [comment] 2024-12-05 16:40
I've reduced this down to a txtar repro for now:

```
# With evalv3, we get an error in both cases
env CUE_EXPERIMENT=evalv3
! exec cue export --with-context -l '_input:' -l 'filename' failure/common.cue failure/case1.cue failure/data.yaml
! exec cue export --with-context -l '_input:' -l 'filename' failure/common.cue failure/case2.cue failure/data.yaml

# But with evalv2, we incorrectly allow case2
env CUE_EXPERIMENT=
! exec cue export --with-context -l '_input:' -l 'filename' failure/common.cue failure/case1.cue failure/data.yaml
! exec cue export --with-context -l '_input:' -l 'filename' failure/common.cue failure/case2.cue failure/data.yaml

-- cue.mod/module.cue --
module: "github.com/davidovich/cue-bug"
language: {
	version: "v0.11.0"
}
-- lib/entry/entry.cue --
package entry

#hasParametersField: {
	parameters: _
}

#nameFromFilename: {
	#in: _

	for _name, _content in #in {
		{
			Name:    _name
		} & _content.parameters
	}
}
-- failure/common.cue --
package failure

import "github.com/davidovich/cue-bug/lib/entry"

// input: "filename": content
_input: [string]: entry.#hasParametersField

#schema: {
	Name:   string
	aField: *false | bool
	bField: string
}

_parameters & #schema
-- failure/case2.cue --
package failure

import "github.com/davidovich/cue-bug/lib/entry"

_parameters: {#in: _input} & entry.#nameFromFilename
-- failure/case1.cue --
package failure

#nameFromFilename: {
	for _name, _content in _input {
		{
					Name: _name
		} & _content.parameters // lift parameters to top level
	}
}
_parameters: {#in: _input} & #nameFromFilename
-- failure/data.yaml --
parameters:
  aField: true
  bField: "value"
  notAllowed: true
```

This is not minimal. However, a couple of things that I have noted:

* As @davidovich points out, the setup in `case2.cue` is required to trigger the problem
* But also, I couldn't seem to reproduce this if I switched the use of `data.yaml` for a `cue import`-ed equivalent (i.e. values placed at the right path

However, I will point out that this bug is fixed with evalv3, so we shouldn't spend too much time trying to work out how/why evalv2 is broken. Other than including a repro like this as a regression test for an "evalv3 win".



> Whilst `evalv3` behaves as you expect here, I'm not actually sure that it is doing "the right thing", because of the following embedding:
> 
> ```
> _parameters & #schema
> ```
> 
> I'm seeking to unravel things a bit here and then get Marcel to opine.

I was incorrect here. The behaviour of evalv3 is correct here, because the value being embedded is the result of `(_parameters & #schema)`, and it's that unification that should fail _before_ the embedding.

**Comment by myitcv** [comment] 2024-12-05 20:17
@rogpeppe has reduced this further:

```
# With evalv3, we get an error.
env CUE_EXPERIMENT=evalv3
! exec cue export --with-context -l '_input:' -l 'filename' x.cue data.json
stderr 'notAllowed: field not allowed'

# But with evalv2, it's incorrectly allowed.
env CUE_EXPERIMENT=
! exec cue export --with-context -l '_input:' -l 'filename' x.cue data.json
stderr 'notAllowed: field not allowed'

-- x.cue --
#schema: aField!: bool

_parameters & #schema
_parameters: #template

#template: {
    #in: _input
    for _name, _content in #in {
        _content.parameters
    }
}

_input: {}

-- data.json --
{
    "parameters": {
        "aField": true,
        "notAllowed": true
    }
}
```

**Comment by myitcv** [comment] 2024-12-06 17:34
On the basis that this is working as intended with evalv3, and that we are shifting nearly all of our efforts towards evalv3, I will mark this as an "evalv3 win". I have created a test locking in the behaviour of both old and new evaluators in https://review.gerrithub.io/c/cue-lang/cue/+/1205343. 

@davidovich as things stand we don't plan to fix the old evaluator; are you in a position to flip to the new evaluator?

**Closed as completed** 2024-12-08 05:53 UTC
Labels: NeedsInvestigation, NeedsInfo, evaluator, evalv3-win
