### ISSUE TITLE
evalv3: severe performance regression

### ISSUE THREAD

**Issue by gotwarlost** [cue-lang/cue#3307] opened 2024-07-18 21:32 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.9.2

go version go1.22.5
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
cue.lang.version v0.9.2
</pre>

### Does this issue reproduce with the latest stable release?

Yes, but only with the new evaluator.

### What did you do?

```
time cue eval ./repro

# real	0m0.058s
# user	0m0.025s
# sys	0m0.017s

time CUE_EXPERIMENT=evalv3 cue eval ./repro

#real	0m16.459s
#user	0m29.155s
#sys	0m11.458s

# This can be made arbitrarily slow by adding more fields to the structs
-- repro/one.cue --
package repro

if features.enabled {
	l0: l1: l2: l3: r1: {
		k1: "v1"
		k2: "v2"
		k3: "v3"
		if addK100 {
			k100: true
		}
		k4: "v4"
		k5: "v5"
		k6: "v6"
		k7: "v7"
		k8: "v8"
	}
	l0: l1: l2: l3: r2: {
		k1: "v1"
		k2: "v2"
		k3: "v3"
		if addK100 {
			k100: true
		}
		k4: "v4"
		k5: "v5"
		k6: "v6"
		k7: "v7"
	}
}
-- repro/two.cue --
package repro

#request: {...}
features: #request.features
addK100:  #request.k100

```

### What did you expect to see?

Evaluation returning sub-second like the old evaluator.

### What did you see instead?

Evaluation takes 16s for the files above. Adding more `[k,v]` fields can make this arbitrarily slow and not return. 

To be clear, on our large package `cue def --inline-imports .` (which is the command I started with) never returns.

Even `cue eval` seems to have the same problem.

**Comment by myitcv** [comment] 2024-07-19 04:32
@gotwarlost thanks very much again for going to the effort of reducing the problem here, and for joining the dots to the original cause (`cue def --inline-imports`).

**Comment by mpvl** [comment] 2024-08-12 17:28
Interesting regression. Upon analysis, this evaluation does not result in a high number of core operation. A very low one indeed, actually. Some profiling is needed here.

**Comment by gotwarlost** [comment] 2024-08-15 18:27
I must be holding something wrong but I don't see the perf improve when running the latest code from master.

```
$ cue version
cue version v0.11.0-0.dev.0.20240815170408-67f508f9935b

go version go1.22.5
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
cue.lang.version v0.11.0

$ time cue eval .

real	0m0.047s
user	0m0.020s
sys	0m0.014s

$ time CUE_EXPERIMENT=evalv3 cue eval .

real	0m20.444s
user	0m24.091s
sys	0m15.002s

```

**Comment by myitcv** [comment] 2024-08-19 15:33
> I must be holding something wrong but I don't see the perf improve when running the latest code from master.

Neither do I. Hence re-opening this issue, @mpvl.

**Comment by cuematthew** [comment] 2024-08-19 16:23
Yep, it was fixed briefly, but it turns out the fix was far too fragile. A better fix is in progress. Apologies.

**Closed as completed** 2024-08-20 11:14 UTC
Labels: NeedsFix, roadmap/performance, evaluator, evalv3
