### ISSUE TITLE
cue/fmt: moving and always adding extra comma in list

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#2525] opened 2023-08-06 01:34 UTC
### What version of CUE are you using (`cue version`)?

0.6.0-rc.1

### What did you do?

```
exec cue fmt file.cue
cmp file.cue golden.cue
-- file.cue --
items: [
	#Site.Ingress,
	#Site.Service,
	#Site.Deployment,
	#Site.Database,
	// #Site.Keycloak
]
-- golden.cue --
items: [
	#Site.Ingress,
	#Site.Service,
	#Site.Deployment,
	#Site.Database,
	// #Site.Keycloak
]
```

### What did you expect to see?

the same file contents

### What did you see instead?

the comma moved from the last list entry to the comment, doing this repeatedly will produce many commas like this

```cue
items: [
	#Site.Ingress,
	#Site.Service,
	#Site.Deployment,
	#Site.Database
	// #Site.Keycloak,,,,,,,,,,,,,
]
```

**Comment by mvdan** [comment] 2023-08-06 02:52
duplicate of https://github.com/cue-lang/cue/issues/1478, I think.

**Closed as not planned by mvdan** 2023-08-06 02:52 UTC
Labels: NeedsInvestigation, Triage
