### ISSUE TITLE
path.Join does not work with values with defaults

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1409] opened 2021-11-29 11:23 UTC
commit 9e7d4d63acf9cfcf7fdc33731dedfe420c0e2689

The following code produces an error, but it should work:

```
import "path"

p: *"hello" | string
q: path.Join([p], path.Unix)
```

It prints this error:

```
q: non-concrete value *"hello" | string for element 0 of string list argument 0:
    ./c.cue:4:4
    ./c.cue:4:15
```

**Comment by rogpeppe** [comment] 2021-11-29 11:25
As a workaround, putting the argument inside a string interpolation causes it to work:

```
q: path.Join(["\(p)"], path.Unix)
```

**Comment by myitcv** [comment] 2021-11-29 13:06
See also https://github.com/cue-lang/cue/issues/1025

**Comment by mpvl** [comment] 2021-11-29 13:53
Duplicate of #1025

**Closed as completed** 2021-11-29 13:53 UTC
Labels: NeedsFix, roadmap/api
