### ISSUE TITLE
Bad import cycle detection

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#2612] opened 2023-09-23 18:13 UTC
### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.0.0-20230825121609-3165a5e1aaec
</pre>

### What did you do?

```
exec cue export -o out.json

-- cue.mod/module.cue --
module: "hof.io/repro"

-- menu.cue --
package menu

import (
	foo "hof.io/repro/foo:menu"
)

toc: [
	{ name: "home", href: "/" },
	foo.toc
]

-- foo/menu.cue --
package menu

name: "foo"
href: "/foo"

children: []
```

### What did you expect to see?

passing test

### What did you see instead?

```
[stderr]
import failed: import failed: package import cycle not allowed:
    ./menu.cue:4:2
    ./menu.cue:4:2
[exit status 1]
FAIL: bad-import-cycle.txt:1: unexpected exec command failure
```

**Comment by mvdan** [comment] 2023-09-24 22:19
With that package layout and import, this looks like a duplicate of https://github.com/cue-lang/cue/issues/2284#issuecomment-1715733260 - there is a cycle here, unless I'm missing something.

**Comment by verdverm** [comment] 2023-09-25 15:01
It is not meant to be the same package, it's more that it is a different folder with the same name (IRL), and has been renamed during import.

**Comment by mvdan** [comment] 2023-09-25 15:04
The child package shares the same package name as the parent, so it's an instance; see https://cuelang.org/docs/concepts/packages/#instances. The child has an implicit dependency on the parent, hence the cycle. #2284 describes this as well.

**Comment by verdverm** [comment] 2023-09-25 15:09
This is where the bizarre import semantics bite people... I don't want it to walk up like that, just because there happen to be some other files around with the same package name in another folder. One would hope that renaming could break the cycle...

When is this default behavior changing?

**Comment by mvdan** [comment] 2023-09-25 15:11
See https://github.com/cue-lang/cue/issues/2486; closing this as a duplicate.

**Closed as not planned by mvdan** 2023-09-25 15:11 UTC
Labels: NeedsInvestigation
