### ISSUE TITLE
docs: document import path syntax

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3303] opened 2024-07-18 11:41 UTC
The import path syntax is not explicitly documented anywhere. The specification documents the fact that the `:name` identifier
comes at the end of the import path, after the package, thus implying that the version part must come prior to that, but we should document the full syntax explicitly, probably as part of the [modules reference](https://cuelang.org/docs/reference/modules/).

**Comment by mvdan** [comment] 2024-08-02 09:34
This appears to have been a duplicate of https://github.com/cue-lang/cue/issues/3184, which already got fixed for v0.10.

**Closed as not planned by mvdan** 2024-08-02 09:34 UTC
Labels: Documentation, modules
