### ISSUE TITLE
Undefined fields should always return bottom (even for implied root struct)

### ISSUE THREAD

**Issue by kcburge** [cue-lang/cue#1714] opened 2022-05-11 23:57 UTC
### What version of CUE are you using (`cue version`)?
master

### Does this issue reproduce with the latest release?
YES

### What did you do?

eval of

```
v: a
```

fails with: failed to build: -:3:4: reference "a" not found

however, eval of:

```
x: {}
v: x.a
```
evaluates without error.

### What did you expect to see?

Given that the top-level is an implicit struct, why would you return an error for undefined fields? I would expect an eval to just show it referencing this unknown field, as the second example above does, and only return an "undefined field: a" error upon cue export (or other concrete output).  The reason I noticed this difference is I was testing disjunctions with multiple defaults:

```
_b: "b"
_c: "c"
v: *_a | (*_b | _c)
```

Which resulted in:

failed to build: -:3:5: reference "_a" not found

But:
```
_x: b: "b"
_x: c: "c"
v: *_x.a | (*_x.b | _x.c)
```
produced: 

```
{"v": "b"}
```

as I expected.

This seems like a bug to me. However, I could see this leading to obvious unreported import errors.  Like referencing "json.Marshal" without importing json.

Related: #1581, #629

**Comment by eonpatapon** [comment] 2022-05-12 09:54
This is a duplicate of #629

See first comment for the difference between `v: a` and `v: x.a`

```
Like with Go, one should distinguish a reference from a selector.

A missing reference, the first y in this case, is a unrecoverable compile-time error. 
It is illegal CUE. CUE cannot evaluate meaningfully without resolving a reference.

This is the only reference of y. The other y's are selectors in the resolved references 
fn and s. These are not compile time errors. As per the CUE spec, these are just errors 
that get eliminated as disjuncts as part of CUE evaluation and thus will not generate 
user-facing errors. In fact, these errors are even resolvable (it is an "incomplete" error), 
as a user may resolve the error by making a configuration more concrete.
```

**Comment by kcburge** [comment] 2022-05-12 14:01
While #629 recognizes the difference in behavior between a "reference" and a "selector", #629 seems to want the below to cause an error (which I disagree with):

```
x: {}
v: x.a
```

I'm saying, to be consistent with how selectors are everywhere else, the below should not print out an error:

```
v: a
```

CUE is not Go.  A CUE file is data with an implied root struct.  "v" and "a" both are selectors on the implicit root struct.  They are not references.

Having said that, I WOULD expect this to fail:

```
[{v: a}]
```
Because this is changing the root object to be instead an array, which cannot have members.

I come from a Ruby background, and I know that as soon as I define any identifier in the top level source code, I know it's actually defining it on an implicit instance of some Object.  To me, CUE is the same way.

The compiler needs to differentiate between a real reference and a selector on the implied default struct, and not fail in the latter situation.

I guess the fundamental problem here is CUE wants to be act like data, but with code semantics (i.e. "references", which data does not have). Example:

```
package root

[{a: 1}]
```

This just looks... weird.  "package", "import", etc. all get special treatment (they are not really part of the data).  Some folks want CUE files to act more like code, where if they reference a undefined (top-level) member, it immediately fails.  My opinion: CUE needs to commit to being data wholeheartedly, and allow those embedding CUE's compiler to flip a strictness switch if they want references to top-level members to fail if undefined (Dagger, etc.). For the rest of the world, an undefined selector (in all situations) returns bottom.

**Comment by kcburge** [comment] 2022-05-12 14:49
Proof "v" is really a selector on the root struct (I know this is invalid code):

```
v: 1
[{a: v}]
```

outputs:
failed to encode: conflicting values [{a:v}] and {[{a:v}],v:1} (mismatched types list and struct)

This code is trying to make the root level object both a struct and an array.  Just wanted t show v being a member of the struct.

**Comment by myitcv** [comment] 2022-05-16 05:19
> #629 seems to want the below to cause an error (which I disagree with):

#629 is talking about _when_ that example should result in an error from a developer experience (DX) perspective. That is to say, there is a distinction between when an unresolved selector should be surfaced as an error to a user or not, and the detection of such an error in the first place. CUE today does _not_ raise an error in such a situation because more CUE can be provided to make that unresolved selector error disappear. However, from a DX perspective, that can (and does) cause real errors to be missed, hence #629. 

@kcburge - I'm going to close this issue and ask that we move discussion to #629. All of the points you are raising above are relevant to that discussion about DX but come, as you point out, from a different perspective. We should feed those perspectives into that discussion.

**Closed as completed by myitcv** 2022-05-16 05:19 UTC
Labels: NeedsInvestigation
