### ISSUE TITLE
nil pointer when running cue get go ...

### ISSUE THREAD

**Issue by richardalberto** [cue-lang/cue#2254] opened 2023-02-08 14:56 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.5
</pre>

### Does this issue reproduce with the latest stable release?
Yes (tested with v0.4.3)

### What did you do?

`cue get go github.com/private-org/kubernetes-api/v1alpha1`

### What did you expect to see?
`cue get go ...` should generate the cue files.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16e3a99]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0113afe90)
	/Users/richardgo/dev/cue/cmd/cue/cmd/root.go:261 +0x7b
panic({0x178ad60, 0x1ddef70})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x212
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc003befc20, {0xc00003a044, 0x32}, 0x0)
	/Users/richardgo/dev/cue/cmd/cue/cmd/get_go.go:438 +0x79
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc003befc20, {0xc00003a044, 0x32}, 0xc000279980)
	/Users/richardgo/dev/cue/cmd/cue/cmd/get_go.go:555 +0xc14
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc003befc20, {0xc00003a044, 0x32}, 0xc000287980)
	/Users/richardgo/dev/cue/cmd/cue/cmd/get_go.go:555 +0xc14
cuelang.org/go/cmd/cue/cmd.extract(0xc000395500, {0xc000331760, 0x1, 0x1})
	/Users/richardgo/dev/cue/cmd/cue/cmd/get_go.go:417 +0x3e5
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003b6000?, {0xc000331760, 0x1, 0x1})
	/Users/richardgo/dev/cue/cmd/cue/cmd/root.go:72 +0xb3
github.com/spf13/cobra.(*Command).execute(0xc0003b6000, {0xc000331730, 0x1, 0x1})
	/Users/richardgo/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a2780)
	/Users/richardgo/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/richardgo/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000395500, {0x3?, 0x3?})
	/Users/richardgo/dev/cue/cmd/cue/cmd/root.go:246 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0x197f610, 0xc00012a008}, {0xc000112050?, 0xc0000061a0?, 0x200000003?})
	/Users/richardgo/dev/cue/cmd/cue/cmd/root.go:183 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
	/Users/richardgo/dev/cue/cmd/cue/cmd/root.go:165 +0x7c
main.main()
	/Users/richardgo/dev/cue/cmd/cue/main.go:24 +0x19
```

**Comment by mvdan** [comment] 2023-02-08 15:02
Thanks for reporting! As far as I can tell, this is a near-identical duplicate of https://github.com/cue-lang/cue/issues/2046, so I'm closing in favor of that thread for the sake of deduplicating :)

**Closed as not planned by mvdan** 2023-02-08 15:02 UTC
Labels: NeedsInvestigation, Triage
