### ISSUE TITLE
Required field within optional list not being validated properly in library

### ISSUE THREAD

**Issue by FletcherCuttingMachShip** [cue-lang/cue#3448] opened 2024-09-13 02:14 UTC
### What version of CUE are you using (`cue version`)?
I am using the following version of the CUE Go library:
```
cuelang.org/go v0.10.0
```
It's worth noting that this issue only exists in the library. The following issue could not be replicated when using the command line tool.

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?
I have the following test:
```go
func Test_cue(t *testing.T) {
	cuectx := cuecontext.New()
	schema := cuectx.CompileBytes([]byte(`
		carrier!: {
			name!: string
			items!: [...{
				name!: string
				description!: string
			}]
		}
	`))

	if err := schema.Validate(); err != nil {
		t.Fatalf("failed to compile schema: %s", err)
	}

	data := cuectx.Encode(map[string]any{
		"carrier": map[string]any{
			"name": "carrier name",
			"items": []map[string]any{
				{
					"name": "item name",
				},
			},
		},
	})

	if err := data.Validate(); err != nil {
		t.Fatalf("failed to encode data: %s", err)
	}

	unified := schema.Unify(data)

	if err := unified.Validate(); err != nil {
		t.Fatalf("failed: %s", err)
	}
}
```

### What did you expect to see?
I expected the test to fail because the `carrier.items.description` field is required but not being provided.

### What did you see instead?
The test passed with no validation errors.

**Comment by mvdan** [comment] 2024-09-17 08:58
This fails as expected with the command line, as long as you want concrete output:

```
! exec cue export in.cue

! exec cue vet -c in.cue

-- in.cue --
carrier!: {
	name!: string
	items!: [...{
		name!: string
		description!: string
	}]
}

carrier: {
    name: "carrier name",
    items: [
    	{
    		name: "item name"
    	}
    ]
}
```

Here is a simplified version of your Go program:

```
package main

import (
	"fmt"

	"cuelang.org/go/cue/cuecontext"
)

func main() {
	ctx := cuecontext.New()
	schema := ctx.CompileString(`
		items!: [...{
			name!: string
			description!: string
		}]
	`)

	if err := schema.Validate(); err != nil {
		panic(err)
	}

	data := ctx.Encode(map[string]any{
		"items": []map[string]any{
			{
				"name": "item name",
			},
		},
	})

	// Both the schema and data are valid on their own.
	if err := schema.Validate(); err != nil {
		panic(err)
	}
	if err := data.Validate(); err != nil {
		panic(err)
	}

	unified := schema.Unify(data)

	if err := unified.Validate(); err != nil {
		fmt.Println(err)
		return
	}
	panic("unexpected success")
}
```

Note how the schema passes validation even when there are required fields which are not present, such as `items` itself. This is because `Validate()` does not require a value to be final and concrete, which allows it to validate schemas and validations on their own. What you want to do is `Validate(cue.Concrete(true), cue.Final())`, which is equivalent to what `cue export` or `cue vet -c` above do, and which does fail:

```
items.0.description: field is required but not present
```

**Comment by mvdan** [comment] 2024-09-17 09:00
I'm going to close this for now because, as far as I'm aware, this is working as intended. The docs even point out your case:

```
// Note that by default not all errors are reported, unless options like
// [Concrete] are used. The [Final] option can be used to check for missing
// required fields.
```

**Closed as not planned by mvdan** 2024-09-17 09:00 UTC
Labels: NeedsInvestigation, Triage
