### ISSUE TITLE
Disjunction Regression in `v0.5.0-beta.5`

### ISSUE THREAD

**Issue by slewiskelly** [cue-lang/cue#2263] opened 2023-02-13 07:05 UTC
### What version of CUE are you using (`cue version`)?

```console
$ cue version
cue version v0.0.0-20230211165554-7d89acd5c44b

go version go1.19.5
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
             vcs git
    vcs.revision 7d89acd5c44bca0c756f76089436ee9913818b03
        vcs.time 2023-02-11T16:55:54Z
    vcs.modified false
```

### Does this issue reproduce with the latest stable release?

The latest stable release (`v0.4.3`) works as expected.

### What did you do?

Consider the following:

```cue
metrics: [...#Metric]

metrics: [{
	id:  "foo"
	avg: 60
}, {
	id:    "bar"
	value: 80
}, {
	uri: "baz"
	avg: 70
}, {
	uri:   "qux"
	value: 90
}]

#Metric: {
	#Source
	#Target
}

#Source:
	#IDSource |
	#URISource

#Target:
	#TargetAverage |
	#TargetValue

#IDSource: {
	id: string
}

#URISource: {
	uri: string
}

#TargetAverage: {
	avg: number
}

#TargetValue: {
	value: number
}
```

### What did you expect to see?

```cue
{
    "metrics": [
        {
            "id": "foo",
            "avg": 60
        },
        {
            "id": "bar",
            "value": 80
        },
        {
            "uri": "baz",
            "avg": 70
        },
        {
            "uri": "qux",
            "value": 90
        }
    ]
}
```

This is the case when using either of the following CUE versions:
- `v0.4.3`
- `v0.5.0-beta.2`

### What did you see instead?

Errors pertaining to `errors in empty disjunction` and `field not allowed`.

I managed to bisect this down to https://review.gerrithub.io/c/cue-lang/cue/+/549079 (5a6bd1910821112123897c2b553b848c15f6eae2).

<details>

<summary>Error</summary>

```log
metrics.0: 2 errors in empty disjunction:
metrics.0.avg: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:5:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:23:2
    ./repro.cue:30:12
metrics.0.id: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:4:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:24:2
    ./repro.cue:34:13
metrics.1: 2 errors in empty disjunction:
metrics.1.id: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:7:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:24:2
    ./repro.cue:34:13
metrics.1.value: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:8:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:23:2
    ./repro.cue:30:12
metrics.2: 2 errors in empty disjunction:
metrics.2.avg: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:11:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:24:2
    ./repro.cue:34:13
metrics.2.uri: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:10:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:23:2
    ./repro.cue:30:12
metrics.3: 2 errors in empty disjunction:
metrics.3.uri: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:13:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:23:2
    ./repro.cue:30:12
metrics.3.value: field not allowed:
    ./repro.cue:1:11
    ./repro.cue:1:14
    ./repro.cue:14:2
    ./repro.cue:17:10
    ./repro.cue:18:2
    ./repro.cue:24:2
    ./repro.cue:34:13
```
</details>

**Comment by slewiskelly** [comment] 2023-02-13 07:12
If I make the following change, the result works, as expected:

```diff
@@ -19,22 +19,16 @@ metrics: [{
 	#Target
 }

-#Source:
-	#IDSource |
-	#URISource
+#Source: {
+	id: string
+} | {
+	uri: string
+}

 #Target:
 	#TargetAverage |
 	#TargetValue

-#IDSource: {
-	id: string
-}
-
-#URISource: {
-	uri: string
-}
-
 #TargetAverage: {
 	avg: number
 }
```

**Comment by mvdan** [comment] 2023-02-13 13:43
This might well be a duplicate of https://github.com/cue-lang/cue/issues/2246, given that the bisect points to exactly the same CL, one of your errors is also "field not allowed", and both use disjunctions with definitions in a very similar way.

It's probably worth keeping this open as a separate issue in case my suspicion is wrong, but we should see if fixing the previously reported regression also fixes this.

**Closed as completed** 2023-03-16 12:48 UTC
Labels: NeedsInvestigation
