### ISSUE TITLE
mod: distinguish direct from indirect dependencies

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2958] opened 2024-03-18 18:08 UTC
When viewing a `cue.mod/module.cue` file, it's useful to be able to
easily distinguish which dependencies are used directly by the local
code and which are only there because some other dependency uses them.

We could distinguish between those two classes of dependency using
comments or attributes added by `cue mod tidy`.

**Comment by mvdan** [comment] 2024-03-18 21:42
Duplicate of https://github.com/cue-lang/cue/issues/2899.

**Closed as not planned by mvdan** 2024-03-18 21:42 UTC
Labels: FeatureRequest, modules
