### ISSUE TITLE
OpenAPI from CUE "if": assertion failed: Environment.up encountered a nil vertex

### ISSUE THREAD

**Issue by shortwavedave** [cue-lang/cue#2619] opened 2023-09-27 15:35 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0

go version go1.20.6
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?
I tried to generate OpenAPI from cuelang that has an if conditional. Here is a minimally reproducible example:

```golang
go mod tidy
go run .

-- go.mod --
module test

go 1.21

require cuelang.org/go v0.6.0

require (
	github.com/cockroachdb/apd/v3 v3.2.0 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	golang.org/x/net v0.8.0 // indirect
	golang.org/x/text v0.8.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"log"

	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/errors"
	"cuelang.org/go/encoding/openapi"
)

func main() {
	ctx := cuecontext.New()
	value := ctx.CompileString(`
#A: {
	if true {
		params: #B
	}
}
#B: int
`)
	if err := value.Err(); err != nil {
		log.Fatal(err)
	}
	_, err := openapi.Generate(value, &openapi.Config{})
	if err != nil {
		log.Fatalf("Error processing file: \n%v", errors.Details(err, nil))
	}
}
``` 

### What did you expect to see?
A OneOf structure

### What did you see instead?
```bash
panic: assertion failed: Environment.up encountered a nil vertex [recovered]
        panic: assertion failed: Environment.up encountered a nil vertex
```

More context in a slack conversation here (https://cuelang.slack.com/archives/CLT4FD7KP/p1695412292491719), but what is provided in this issue is the crux.

**Comment by mvdan** [comment] 2024-03-18 10:05
I believe we now have an even smaller reproducer of the same bug at https://github.com/cue-lang/cue/issues/2911#issuecomment-2003361065, and I believe these panics have the same root cause, so for now I'm going to close this one as a duplicate to make sure all details and discussion happens in a single place. Once we have a fix, we'll make sure that your panic involving openapi is also fixed, and reopen this issue in case I was wrong.

Thank you again for providing a reproducer, and apologies for the slowness!

**Closed as not planned by mvdan** 2024-03-18 10:05 UTC
Labels: NeedsFix
