### ISSUE TITLE
encoding/json: error positions do not reflect position of error

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2776] opened 2024-01-22 14:24 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```
exec go mod tidy
# The syntax error is on line 4, so we expect
# error message to include that.
exec go run main.go
stderr 'test\.json:4'
-- go.mod --
module m

go 1.21

require cuelang.org/go v0.7.0
-- test.json --
{
	"x": 2
}
	{"unterminated",}
-- main.go --
package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"log"
	"os"

	"cuelang.org/go/cue/errors"
	"cuelang.org/go/encoding/json"
)

//go:embed test.json
var testJSON []byte

func main() {
	dec := json.NewDecoder(nil, "test.json", bytes.NewReader(testJSON))
	// Sanity check that the first value can be extracted OK.
	_, err := dec.Extract()
	if err != nil {
		log.Fatalf("first: %v", err)
	}
	_, err = dec.Extract()
	fmt.Printf("error: %v\n", err)
	fmt.Printf("positions: %v\n", errors.Positions(err))
	fmt.Println("errors.Print: ")
	errors.Print(os.Stdout, err, nil)
}
```

### What did you expect to see?

A passing test

### What did you see instead?

The position of the error bears no relationship to the position that the syntax error actually occurred at.
It always says it's at line 1, column 1.

```
# The syntax error is on line 4, so we expect
# error message to include that. (0.258s)
> exec go run main.go
[stdout]
error: invalid JSON for file "test.json": invalid character ',' after object key
positions: [test.json:1:1]
errors.Print: 
invalid JSON for file "test.json": invalid character ',' after object key:
    test.json:1:1
> stderr test,json:4
FAIL: /tmp/testscript3302001597/jsonpos.txtar/script.txtar:5: no match for `test,json:4` found in stderr
```

**Comment by mvdan** [comment] 2024-01-23 09:43
Is `test,json:4` in the testscript a typo?

**Comment by rogpeppe** [comment] 2024-01-30 11:37
> Is `test,json:4` in the testscript a typo?

Yup, fixed.

**Comment by mvdan** [comment] 2024-08-08 13:04
Note that you created a duplicate of this issue in #3317, now fixed, but this reproducer above shows that we're not fully fixed for NDJSON or JSONL inputs. I'll send a follow-up fix using this tracking issue.

**Closed as completed** 2024-08-12 08:56 UTC
Labels: NeedsFix
