### ISSUE TITLE
Add dynamic labels section to cue grammar description 

### ISSUE THREAD

**Issue by kghenderson** [cue-lang/cue#2017] opened 2022-10-18 16:40 UTC
This is referring to the form of syntax: `(x)` as a label, which is suggested in favour of the interpolated string form: `"\(x)"`

e.g. 
`(x): { }`

the dagger documentation describes it as follows:
https://docs.dagger.io/1215/what-is-cue/#non-interpolated-string
though this seems to be covered as an operand/value, the label case appears to be missing.

thank you.

**Comment by mvdan** [comment] 2023-06-14 14:27
Duplicate of https://github.com/cue-lang/cue/issues/2267? That one is newer, but has more detail :)

**Comment by mvdan** [comment] 2023-06-14 14:28
Closing per the above.

**Closed as not planned by mvdan** 2023-06-14 14:28 UTC
Labels: NeedsInvestigation
