### ISSUE TITLE
load.Instances doesn't accept YAML

### ISSUE THREAD

**Issue by sjwl** [cue-lang/cue#2262] opened 2023-02-11 02:55 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.2

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH arm64
            GOOS darwin

</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

```golang
import (
  "cuelang.org/go/cue/load"
  "cuelang.org/go/cue/cuecontext"
)
...
cueCtx := cuecontext.New()
inst := load.Instances("foo.yaml", nil)[0]
cueSchema := cueCtx.BuildInstance(inst).Validate(cue.Concrete(true)); err != nil {
  return fmt.Errorf("validate fail: %s", errors.Details(err, nil))
}
```
`foo.yaml`
```yaml
foo: bar
```

### What did you expect to see?

no errors

### What did you see instead?

```
Error: validate fail: foo: reference "bar" not found:
    1:6
```

**Comment by myitcv** [comment] 2023-06-13 16:35
I believe this is a duplicate of https://github.com/cue-lang/cue/issues/1410, so closing on that basis. Please shout if you disagree.

**Closed as completed by myitcv** 2023-06-13 16:35 UTC
Labels: FeatureRequest, NeedsInvestigation, cue/load
