### ISSUE TITLE
cmd/fmt: option to emit the compact, single-line form of a given CUE file

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2492] opened 2023-07-13 18:01 UTC
**Is your feature request related to a problem? Please describe.**

I'm writing a web service that accepts its per-request config in CUE from the user, and the best channel to provide this is via a URL parameter.

This would benefit greatly from being passed a single-line form of the config.

**Describe the solution you'd like**

I /believe/ that (modulo `--inline-imports` or other niggles) there exists a single-line, comma-based representation of any CUE text.

I'd like `cue fmt` to learn an option that's the equivalent of `jq -c` (which provides its JSON output in a compact, single-line format) - i.e. with all human-friendly white-space removed, commas inserted where appropriate, and multi-line strings expressed with `\n`'s in a way that's unambiguous to the next evaluator of the text.

It would be great if this could be nicely round-tripped back to "normal" CUE by `cue fmt`, but I don't think that should be a requirement, as I believe there are corner cases where information is lost by the compacting, hence compacted texts can't be un-compacted to their original form 100% of the time.

**Describe alternatives you've considered**

Right now, I need users to mutate their config with something horrible, such as

```shell
$ cat file.cue  | tr '\n' ',' | tr -s , | sed -E 's/\[,/[/g;s/\{,/\{/g; s/,[[:space:]]*\}/\}/g' 
```

.. and even this horror show isn't optimal, as it doesn't know how to remove unnecessary white-space, nor does it work correctly with multi-line strings.

Another alternative is to URL encode not only all URL-unsafe characters but also all newlines and white-space in the original text, and pass it through in that form. This will bloat the URL parameter's size rather significantly.

**Additional context**

I'm unsure if CUE comments break my assertion that every CUE text has a single, one-line form. In my use-case, stripping comments from the compact form would be not only acceptable but desireable.

**Comment by myitcv** [comment] 2023-07-13 18:53
Appears to be a duplicate of https://github.com/cue-lang/cue/issues/2477.

**Closed as completed by myitcv** 2023-07-13 18:53 UTC
Labels: FeatureRequest

**Comment by jpluscplusm** [comment] 2023-07-13 18:56
I'd found #2477, and read it as being JSON/YaML-focussed. If there's enough context in/behind it to track the compact CUE format need as well, I agree this is a dupe.

**Comment by myitcv** [comment] 2023-07-14 13:20
Yes, no reason for #2477 to be specific to JSON/Yaml... I think it can and should be generalised.
