### ISSUE TITLE
cuelang.org: enable the preprocessor to format all multi-document YAML files

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2666] opened 2023-10-27 14:38 UTC
**Is your feature request related to a problem? Please describe.**

We have existing cuelang.org content which, when copied over to alpha, needs to have a new `#nofmt` line added:

```
{{{with code "en" "client-side-validation"}}}
#nofmt(ranges.yaml)
! exec cue vet ranges.yaml check.cue
cmp stderr output
-- check.cue --
min?: *0 | number    // 0 if undefined
max?: number & >min  // must be strictly greater than min if defined.
-- ranges.yaml --
min: 5
max: 10
---
min: 10
max: 5
-- output --
max: invalid value 5 (out of bound >10):
    ./check.cue:2:16
    ./ranges.yaml:5:7
{{{end}}}
```

Without the `#nofmt` line, the preprocessor complains:

```
$ _scripts/runPreprocessor.bash execute
cuelang.org/content/docs/concept/data-validation-use-case/en.md:31:8: failed to run /home/user/bin/docker run --rm -i -e USER_UID=1000 -e USER_GID=1000 preprocessor:6737cccc9f796ca2aee8f8d2bb769c3cc3d28646cede57309f24310407b51610 -- cue export --out=yaml yaml: -: exit status 1
   max: conflicting values 5 and 10:
     -:2:7
     -:5:7
   min: conflicting values 10 and 5:
     -:1:7
     -:4:7
cuelang.org/content/docs/concept/data-validation-use-case/en.md:31:8: failed to format files: in error
terminating because of errors
```

This appears to be because the preprocessor uses `cue export` as a cheap YAML formatter, in a manner which can't cope when **all** documents in a multi-document YAML file don't unify successfully.

**Describe the solution you'd like**

I'd like the preprocessor to cope with multi-document YAML files that don't all unify successfully.

**Describe alternatives you've considered**

I've included a `#nofmt` line.

**Additional context**

n/a

**Comment by myitcv** [comment] 2023-10-27 16:28
This could be solved with:

```
exec cue export --list --out text -l x: -e 'yaml.MarshalStream(x)' yaml: ranges.yaml
cmp stdout stdout.golden

-- ranges.yaml --
min: 5
max: 10
---
min: 10
max: 5
-- stdout.golden --
min: 5
max: 10
---
min: 10
max: 5

```

**Comment by myitcv** [comment] 2024-05-01 14:11
This is effectively a dupe of the newly repurposed https://github.com/cue-lang/cue/issues/2609, so closing this issue.

**Closed as completed by myitcv** 2024-05-01 14:11 UTC
Labels: FeatureRequest, cuelang.org
