### ISSUE TITLE
EscapeHTML=false doesn't work when exporting JSON

### ISSUE THREAD

**Issue by harpratap** [cue-lang/cue#1243] opened 2021-09-01 13:20 UTC
### What did you do?
test.cue

```
x: "&<>"
```

```
cue eval test.cue
x: "&<>"
cue export test.cue
{
    "x": "\u0026\u003c\u003e"
}
cue export test.cue --escape
{
    "x": "\u0026\u003c\u003e"
}
```

### What did you expect to see?

Go's `encoding/json` will encode `&` `<` and `>` in utf-8 by default and this can be turned off by setting [SetEscapeHTML](https://pkg.go.dev/encoding/json#Encoder.SetEscapeHTML) as `false`, which is what the `--escape` flags does [when encoding to JSON](https://github.com/cue-lang/cue/blob/master/internal/encoding/encoder.go#L167) but it doesn't seem to be working as expected. I expect this output -
```
{
    "x": "&<>"
}
```

**Comment by verdverm** [comment] 2021-09-01 20:20
```
$ grep -Rn flagEscape
cue/cmd/export.go:99:   cmd.Flags().Bool(string(flagEscape), false, "use HTML escaping")
cue/cmd/flags.go:39:    flagEscape      flagName = "escape"
```

Based on this grep, I suspect that the flag never makes it to the config object here: https://github.com/cue-lang/cue/blob/master/cmd/cue/cmd/export.go#L105

`parseArgs` probably needs an update

I also noticed the yaml encoder has the same issue, but only outputs `&<>` regardless of `--escape=true/false`

**Comment by harpratap** [comment] 2021-09-02 04:43
@verdverm I had the same hunch, but `escapeHTML` is set to `false` by default anyway. I also forced the `cfg.EscapteHTML` to false and yet got the same results. Also confirmed that when marshalling happens the json module gets the correct `false` flag. So something else seems broken here

**Comment by verdverm** [comment] 2021-09-02 20:00
I can confirm that the escape flag is not being stored into the encConfig object. So that needs a fix.

```
diff --git a/cmd/cue/cmd/common.go b/cmd/cue/cmd/common.go
index 94011825..7021569a 100644
--- a/cmd/cue/cmd/common.go
+++ b/cmd/cue/cmd/common.go
@@ -711,6 +711,7 @@ func (b *buildPlan) parseFlags() (err error) {
                AllErrors: flagAllErrors.Bool(b.cmd),
                PkgName:   flagPackage.String(b.cmd),
                Strict:    flagStrict.Bool(b.cmd),
+               EscapeHTML: flagEscape.Bool(b.cmd),
        }
        return nil
 }
```

This may be an additional and separate issue from the encoders use of the boolean value. I can also confirm that `cue export` output is always escaped regardless of the JSON encoder setting for this.

I believe this is because `json.Encode` calls `json.Marshal` and `cue.Value` has a custom `MarshalJSON` function which calls back into the module `json.Marshal` function without any of the config from the original encoder.

**Comment by mpvl** [comment] 2021-11-23 13:32
The real issue is that the flag is not available for Marshaling the specific CUE value  as the json encoder does not pass that information through, it seems.

Probably not that easy to fix in a non-hacky way.

**Comment by rogpeppe** [comment] 2022-04-13 11:41
Yeah, I believe that this isn't possible to fix until there's a new JSON encoder that allows access to those fields. FYI @dsnet

**Comment by imclem** [comment] 2022-04-29 15:00
Hi ! Is there a workaround for this issue ?

**Comment by sahroshan** [comment] 2023-01-24 09:51
is there any timeline for this?

**Comment by mvdan** [comment] 2023-01-24 09:53
There isn't a workaround right now. I'm looking at this now, as I believe there is a way for us to fix it without changes in upstream Go, but I can't promise a timeline.

**Comment by mvdan** [comment] 2023-04-07 09:51
This should now be fixed in master, which will be tagged as the first v0.6 alpha soon.

**Closed as completed** 2023-04-07 09:51 UTC
Labels: NeedsFix, NotNow, encoding
