### ISSUE TITLE
cuelang.org: contributing link should directly point to GitHub's CONTRIBUTING.md

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1696] opened 2022-05-05 15:12 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
bd9ae5371cc23c54cb3cb90c0bd5a1fa4d82bc92
</pre>

### Does this issue reproduce with the latest release?

n/a

### What did you do?

Linked to the contribution guide when creating a PR:

<img width="324" alt="Screenshot 2022-05-05 at 16 00 34" src="https://user-images.githubusercontent.com/3374574/166952809-79154561-822e-4f18-bd3c-65f9fcd29f5e.png">

### What did you expect to see?

The contents of the actual contribution guide, content that is currently sitting within https://github.com/cue-lang/cue/blob/master/doc/contribute.md.

### What did you see instead?

Out of date information regarding the use of Gerrit, with an onward link to the actual guide at https://github.com/cue-lang/cue/blob/master/doc/contribute.md.

The problem from my perspective:

1. If there are any changes to the contribution guide in https://github.com/cue-lang/cue/blob/master/doc/contribute.md, these are not flagged to people when creating PRs as "the contribution guide has changed since you last submitted a PR".
2. People have to needlessly click through to the actual contribution guide
3. The content in https://github.com/cue-lang/cue/blob/master/CONTRIBUTING.md and https://cuelang.org/docs/contribution_guidelines/ isn't actually that useful by itself; the reader invariably has to click through to the actual contribution guide for more information.

### Suggestion

* Move the content in https://github.com/cue-lang/cue/blob/master/doc/contribute.md to https://github.com/cue-lang/cue/blob/master/CONTRIBUTING.md, and deprecate the former by including a link to the latter. 
* Update the text and links on https://cuelang.org/docs/contribution_guidelines/ to point directly to https://github.com/cue-lang/cue/blob/master/CONTRIBUTING.md

**Comment by mvdan** [comment] 2024-05-14 20:59
> Move the content in https://github.com/cue-lang/cue/blob/master/doc/contribute.md to https://github.com/cue-lang/cue/blob/master/CONTRIBUTING.md, and deprecate the former by including a link to the latter.

This was done in https://review.gerrithub.io/c/cue-lang/cue/+/556350 in July 2023 :) It seems like we had the same thinking.

> Update the text and links on https://cuelang.org/docs/contribution_guidelines/ to point directly to https://github.com/cue-lang/cue/blob/master/CONTRIBUTING.md

That page appears to be https://cuelang.org/docs/reference/contribution-guidelines/ now, maintained at https://github.com/cue-lang/cuelang.org/blob/master/hugo/content/en/docs/reference/contribution-guidelines/index.md. I'm honestly a bit worried that we seem to have a duplicate of CONTRIBUTING.md in another repo. It should be only on GitHub. cc @jpluscplusm

**Comment by mvdan** [comment] 2024-05-14 21:00
That is, I think the "Contributing" link on the website (at the bottom) should link to the markdown file on GitHub directly.

**Comment by jpluscplusm** [comment] 2024-05-15 13:52
> I'm honestly a bit worried that we seem to have a duplicate of CONTRIBUTING.md in another repo.
> It should be only on GitHub.

If we choose to have only a single, authoritative place for the contribution guidelines which *isn't* on cuelang.org, I'd suggest we should still have some page on the site to act as a jumping off point. So that the link in the page footer (and any other links on the site) don't take the reader immediately to GitHub, but instead reach a very short page containing a preamble such as  ...

```
Contributions to the CUE project are welcome from everyone.
The project's contribution guidelines are on GitHub: <URL link that makes it clear you're about to leave the site>.
```

**Comment by mvdan** [comment] 2024-05-15 14:00
I would personally disagree with that; if I want to read the contribution guide, I don't want to have to click twice to actually get to the content, which lives on GitHub. Paul shared a similar thought in the original post:

> People have to needlessly click through to the actual contribution guide

What is your worry? That clicking on the link takes me outside the website? "About > Download" in the footer would have the same issue, presumably, but I don't think it actually is a problem.

The alternative would be to move the content so that it is not on the main cue GitHub repo, but that's definitely not right, as it would no longer be shown in the GitHub UI when viewing the repository sidebar or opening a PR or issue.

**Comment by jpluscplusm** [comment] 2024-05-15 14:08
> What is your worry? That clicking on the link takes me outside the website?

Yes, but it's a small concern that I don't feel particularly strongly.

I'll let you folks let me know what pages we want to exist, and make the changes accordingly.

**Comment by myitcv** [comment] 2024-05-21 10:26
I think linking directly to the GitHub contribution guide is fine. Otherwise we're creating work for ourselves by having another page and forcing the user to click twice.

**Closed as completed** 2024-05-22 15:15 UTC
Labels: Documentation, NeedsFix, cuelang.org
