### ISSUE TITLE
cue/fmt: comma added after comment

### ISSUE THREAD

**Issue by nxcc** [cue-lang/cue#2653] opened 2023-10-23 11:13 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0

go version go1.20.6
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
yes

### What did you do?

`testscript test.cue`

test.cue:
<pre>
exec cue fmt test.cue
cmp stdout test.cue

-- test.cue --
a: [
	"b" + "c"
	//d
]
</pre>

### What did you expect to see?
PASS

### What did you see instead?
FAIL: ... stdout and test.cue differ
a comma is added after the comment; when run multiple times outside testscript, an additional comma is added on every run

**Comment by mvdan** [comment] 2023-10-23 15:28
Appears to be a duplicate of https://github.com/cue-lang/cue/issues/1478, I think.

**Closed as not planned by mvdan** 2023-10-23 15:28 UTC
Labels: NeedsInvestigation, Triage
