### ISSUE TITLE
missing comments in yaml encoder

### ISSUE THREAD

**Issue by sahroshan** [cue-lang/cue#2456] opened 2023-06-24 09:24 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.5.0
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?
```go


package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/encoding/yaml"
)

const val = `
// will it appear in yaml
i: int | *123
`

func main() {
	var (
		c *cue.Context
		v cue.Value
	)

	// create a context
	c = cuecontext.New()

	// compile some CUE into a Value
	v = c.CompileString(val)
	yamlSkeleton, _ := yaml.Encode(v)
	fmt.Println(string(yamlSkeleton))
}



```

### What did you expect to see?
```yaml
# will it appear in yaml
i: 123
```

### What did you see instead?
```yaml
i: 123
```

## I tried debugging the issue. Below are my findings.

we are converting converting `cue.Value` to `ast.Node` at https://github.com/cue-lang/cue/blob/d780488159bd082f9f9d027ab42dd4d9b5d95d5e/encoding/yaml/yaml.go#L84. 

The `ast.Node` supports comment https://github.com/cue-lang/cue/blob/d780488159bd082f9f9d027ab42dd4d9b5d95d5e/cue/types.go#L984 .

### FROM:
https://github.com/cue-lang/cue/blob/d780488159bd082f9f9d027ab42dd4d9b5d95d5e/encoding/yaml/yaml.go#L84

### TO:

```go
n := v.Syntax(cue.Final(), cue.Docs(true))
```

**Comment by mvdan** [comment] 2023-06-24 17:45
I believe this is a duplicate of https://github.com/cue-lang/cue/issues/1180 :)

**Comment by mvdan** [comment] 2023-06-26 06:54
Closing for now.

**Closed as not planned by mvdan** 2023-06-26 06:54 UTC
