### ISSUE TITLE
panic: cmd/cue/cmd.mkRunE init ran twice

### ISSUE THREAD

**Issue by jakub-borusewicz** [cue-lang/cue#3458] opened 2024-09-21 09:12 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.10.0
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

I've written simple pre-commit hook, which uses cue from go script. Here is main file of the repo:
https://github.com/jakub-borusewicz/cue-auto-export/blob/master/main.go

I'm running `Command.Execute()` in loop, which raises error here:
https://github.com/cue-lang/cue/blob/master/cmd/cue/cmd/root.go#L96

### What did you expect to see?
I would expect being able to run cue command directly from go multiple times, or maybe some way of easily running in-code analog of it without this restriction (I didn't find anything similar).

In my case there is no way around it, since pre-commit runs hooks in such a way that it will accept multiple input files at one time.

### What did you see instead?
```
panic: cmd/cue/cmd.mkRunE init ran twice
```

**Comment by jseeley78** [comment] 2024-10-16 05:47
I had a similair issue and had to rollback to v0.9.2 to resolve, commenting so I can follow, but let me know if you need any additional details.

**Comment by mvdan** [comment] 2024-10-16 15:45
Apologies for the slow response here; even though this bug was filed as a panic, it flew under my radar.

I have sent a fix with a regression test in https://review.gerrithub.io/c/cue-lang/cue/+/1202646; does that work for you? It's a straight revert, so I think it should.

We are aiming for releasing v0.11.0 in early November, with the first release candidate before the end of the month. Hopefully you can upgrade straight to either of those, and since they will happen pretty soon, I currently lean against backporting this fix into v0.10.1. We also don't have any other fixes which are severe enough to warrant backporting, as far as I'm aware.

Does that sound reasonable?

**Comment by jakub-borusewicz** [comment] 2024-10-16 20:04
@mvdan sounds good, thanks!

**Comment by mvdan** [comment] 2024-10-17 11:01
The fix is in master :)

**Closed as completed** 2024-10-17 11:00 UTC
Labels: NeedsFix, panic
