### ISSUE TITLE
evaluator: unable to close list value

### ISSUE THREAD

**Issue by bozaro** [cue-lang/cue#2504] opened 2023-07-26 11:42 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230628071453-b6a32da097fc

go version go1.20.5
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision b6a32da097fce5f9c960ad0a02da51efb18de2fd
        vcs.time 2023-06-28T07:14:53Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

cue export list.cue (https://cuelang.org/play/?id=l-k_Vqvpg5k#cue@export@cue)
```
package x

#Foo: {
	l: [...string]
}

#Bar: #Foo
#Bar: {
	l: [...string] | *["bar"]
}

#Baz: #Foo
#Baz: {
	l: [...string] | *close(["baz"])
}

foo: #Foo
bar: #Bar
baz: #Baz
```

### What did you expect to see?
```
foo: {
	l: []
}
bar: {
	l: ["bar"]
}
baz: {
	l: ["baz"]
}
```

### What did you see instead?
```
foo: {
	l: []
}
bar: {
	l: ["bar"]
}
baz: {
	l: []
}
```

**Comment by myitcv** [comment] 2023-07-26 13:34
The issue here is that `close()` does not accept a list value. Hence that element of the disjunction in `#Baz` is eliminated, leaving you with `[]`. 

https://github.com/cue-lang/cue/issues/1999 captures making lists open by default, at which point `close()` will have meaning for a list value. 

I don't think we plan to do anything regarding close before then, so I will close this issue as "working as intended".

**Closed as completed by myitcv** 2023-07-26 13:34 UTC
Labels: WorkingAsIntended
