### ISSUE TITLE
Ho to handle conflicts in CUE

### ISSUE THREAD

**Issue by SephVelut** [cue-lang/cue#1208] opened 2021-08-16 11:15 UTC
I don't think this use case is supported, so here goes.

For me, 99% of all issues I have with configuration management comes from conflicts between similar configs. Here is a simple example of a conflict.

Let's say I a fictitious program that reads configuration files and sets iptables firewall rules accordingly.
ConfigFile1 states that port 8000 should be OPEN.
ConfigFile2 states that port 8000 should be CLOSED.

That is an obvious conflict. What's worse, it could be idempotent, if the program reads the config files in the exact same order each time. First opening, then closing, every time. Then we never get to discover through inconsistent behavior that something fishy is going on. This accounts for nearly all of my configuration woes. 

Here is an example of another type of conflict.
ConfigFile1 states that id be INCREMENTED.
ConfigFile2 states that id be INCREMENTED.

Due to ConfigFile2 being a very sneaky file, somewhere deep in the directory structure, we never discover this conflict, and id gets incremented twice, when the configuration was only meant to do it once. Duplication of effort.

Another type of conflict can be redundancy. Different from duplication, but this one, at least, I think Cue already handles. 

Dealing with conflicts where a value is different for two keys of the same name is easy.
{key1: val1} conflicts with {key1: val2}

But what about when the logic is more complex? 
{key1: "open"} ???? {key1: "close"}
I would love to be able to define a schema that describes maybe a union or something to make the values exclusive to variants.
enum Value { OPEN, CLOSE }
{key1: Value::OPEN} conflicts with {key1: Value::CLOSE}

It would be really nice too, if when handling conflicts, you can annotate key/value pairs to inform on which conflicts are to be ignored. CSS does this with the "!" override. 
{key1: Value::OPEN} and {key1: Value::CLOSE ! } Exclamation overrides, so no conflict. Though, without unification, this then becomes dependent on the order the configs are read.

**Comment by IMBlues** [comment] 2021-09-10 10:10
I have similar needs.

In the configuration definition, hope to provide configurations of different priorities.

### An immature idea
```yaml
global_labels: {
  some-common-key: "default-values-for-every-module"
}

local_labels: {
  # like css ?
  !some-common-key: "for-specific-one"
}

# local_labels has a higher priority and will directly override, won't conflict
pod_labels: global_labels & local_labels
```

**Comment by eadlam** [comment] 2021-09-11 05:16
**Conflicting Values**

I think your example falls specifically within the problem space that the [cue lattice solves](https://cuelang.org/docs/concepts/logic/). 

### Example: Port Conflict 1
A field is redefined in separate files with conflicting values.

**ConfigFile1.cue**
```
port: "8000": "OPEN"
```

**ConfigFile2.cue**
```
port: "8000": "CLOSED"
```

**Result**
```
$ cue export ConfigFile1.cue ConfigFile2.cue 
port."8000": conflicting values "CLOSED" and "OPEN":
    ./ConfigFile1.cue:2:13
    ./ConfigFile2.cue:2:13
```

### Example: Port Conflict 2
Different fields specify values which should be consistent
**ConfigFile.cue**
```
section1: port: "8000": "OPEN"
section2: section1 & {
    port: "8000": "CLOSED"
}

```
**Result**
```
$ cue export ConfigFile.cue
section2.port."8000": conflicting values "CLOSED" and "OPEN":
    ./ConfigFile1.cue:2:25
    ./ConfigFile1.cue:3:11
    ./ConfigFile1.cue:4:19
```

**Redundant execution of INCREMENT**
This sounds like a class of problems that arise with runtime evaluation of config logic. For convenience, you split a single config into multiple files, but conceptually, they are meant to represent a single monolithic config file. During runtime evaluation, you have an implicit expectation that the configs will first be merged and then ingested, but you can't explicitly see that merge, and thus you are surprised when it turns out that they were not merged, and INCREMENT is being called twice. This gets even more complicated if your configs contain programmatic logic that needs to be evaluated as well. The solution is to "materialize" your configs in a compile-time step, with the output being a single static file that you can look at, diff, and commit to version control. Then your software ingests that single materiazed config file.

Cue is also designed for this. For example:   

**ConfigFile1.cue**
```
id: incremented: true
```

**ConfigFile2.cue**
```
id: incremented: true
```

**Materialized**
```
$ cue export ConfigFile1.cue ConfigFile2.cue 
{
    "id": {
        "incremented": true
    }
}
```

Even though id is specified to be incremented twice, when exported the materialized json only contains that specification once. 

**Default Values**
Cue supports this. To use @IMBlues example:

**ConfigFile.cue**
```
global_labels: {
  some_common_key: string | *"default-values-for-every-module"
  some_other_common_key: string | *"other-default-value-for-every-module"
}

local_labels: {
  some_common_key: "for-specific-one"
}

pod_labels: global_labels & local_labels
```

**Result**
```
$ cue export ConfigFile.cue
{
    "global_labels": {
        "some_common_key": "default-values-for-every-module",
        "some_other_common_key": "other-default-value-for-every-module"
    },
    "local_labels": {
        "some_common_key": "for-specific-one"
    },
    "pod_labels": {
        "some_common_key": "for-specific-one",
        "some_other_common_key": "other-default-value-for-every-module"
    }
}
```

Aside from defaults, cue does not support the common inherit/override pattern. The cue lattice is the alternative to this pattern, and this is a feature not a bug. It eliminates one of the biggest problems in configuration management: finding that a field has an unexpected value and then struggling to track down the final override that sets that value. You should read more about it here, as it's one of the main value propositions of cue: https://cuelang.org/docs/concepts/logic/#default-values

**Closed as completed** 2021-10-26 13:42 UTC
Labels: FeatureRequest
