### ISSUE TITLE
evalv3: error in call to strings.SliceRunes: non-concrete value _

### ISSUE THREAD

**Issue by nxcc** [cue-lang/cue#3584] opened 2024-11-21 15:10 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.11.0

go version go1.23.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.11.0
</pre>

### Does this issue reproduce with the latest stable release?
yes

### What did you do?
testscript: [bug.txtar.txt](https://github.com/user-attachments/files/17847881/bug.txtar.txt)

```
env CUE_EXPERIMENT=evalv3
exec cue export -e testgen.objects .

-- build.cue --
package postgresql
testgen: {
	CONFIG = #config: {
		values: VALUES
		...
	}
	CfgTmpl: {[string]: {
		#config: CONFIG
		...
	}}
	_objects: {
		//ConfigMap: testlib.#ConfigMap & CfgTmpl & configMap
		ConfigMap: testlib.#ConfigMap & CfgTmpl & configMap
		Secret:    CfgTmpl & secret
	}
	objects: [
		for allOfKind in _objects
		for object in allOfKind {
			object
		},
	]
}
configMap: {}
secret: {}
VALUES=values: {}
testlib: {}

-- testlib.cue --
package postgresql

import (
	"encoding/json"
	"list"
	"strings"
	"crypto/sha512"
	"encoding/base64"
	"encoding/hex"
	"regexp"
)

testlib: {
	#ConfigMap: [ID=string]: this={
		metadata: {
			name: ID + "-" + (#shortHash & {in: json.Marshal(this.data)}).out
		}
		...
	}
}

#shortHash: {
	in:  string
	len: *6 | int
	data: json.Unmarshal('\(in)')
	out: strings.SliceRunes(
		regexp.ReplaceAll( "[^a-z0-9]",
		base64.Encode( null,
		sha512.Sum512(
		'\(strings.Join([
			for _, k in list.SortStrings( [for k, _ in data {k}]) {
				k + ":" + hex.Encode(data[k])
			},
		], "\n"))',
		)), ""),
		0, len)
}

-- resources.cue --
package postgresql

values: {}

configMap: "postgresql-env": {
	#config: {...}
	data: {
		FOO: "BAR"
	}
}
```

### What did you expect to see?
<pre>PASS</pre>

### What did you see instead?
<pre>
...
out: error in call to strings.SliceRunes: non-concrete value _:
    ./testlib.cue:26:7
...
</pre>

**Comment by myitcv** [comment] 2024-12-08 10:36
Thanks @nxcc for the report. Confirmed with f99441ac39a2.

**Comment by mpvl** [comment] 2024-12-09 16:09
Significantly smaller reproducer:
```
import "strings"

ref: out
trigger: *6 | 5
out: strings.SliceRunes("ABC", 0, trigger)
```

This seems to be an issue related to disjunctions. Might be related to #3415

**Comment by mpvl** [comment] 2024-12-24 15:59
Fixed by  https://cuelang.org/cl/1206321

**Closed as completed by mpvl** 2024-12-24 15:59 UTC
Labels: NeedsFix, evaluator, evalv3
