### ISSUE TITLE
cue/format: can print invalid list syntax when there's a comment

### ISSUE THREAD

**Issue by rileyp2000** [cue-lang/cue#1774] opened 2022-06-23 18:56 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.4.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
```
cue fmt x.cue
-- x.cue --
#something: {
	p_key: string
}

ec: [
	#something & {
		p_key: "foo"
	},

	// #something & {
	//      p_key: "bar"
	// },

	#something & {
                p_key: "baz"
        }
]
```

### What did you expect to see?
```
#something: {
	p_key: string
}

ec: [
	#something & {
		p_key: "foo"
	},

	// #something & {
	//      p_key: "bar"
	// },

	#something & {
                p_key: "baz"
        }
]
```
Or something similar that is still valid cue.

### What did you see instead?
```
#something: {
	p_key: string
}

ec: [
	#something & {
		p_key: "foo"
	}

	// #something & {
	//      p_key: "bar"
	// },,

	#something & {
		p_key: "baz"
	},
]
```
Which obviously results in invalid cue as the comma got removed from the `foo` item in the list. This issue does not occur if the items in the list do not utilize `#something` (i.e. no `#something &`) on each item.

**Comment by mvdan** [comment] 2022-06-24 12:44
I can confirm on `cue version v0.4.4-0.20220622103956-41ceff3c78eb linux/amd64`. Another way to write the test is that the command fails when run a second time, due to the invalid syntax.

**Comment by mvdan** [comment] 2022-06-24 12:46
Actually, this is a duplicate of https://github.com/cue-lang/cue/issues/1478. You're just ending up with invalid syntax because the list has more than one element - but at its core, it's still the same bug. The problem is that the commas get added to the comment for some reason.

**Closed as not planned by mvdan** 2022-06-24 12:46 UTC
Labels: NeedsFix, fmt
