### ISSUE TITLE
CUE eval directory path panics

### ISSUE THREAD

**Issue by kharf** [cue-lang/cue#2983] opened 2024-03-23 09:56 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.0

go version go1.22.1
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?
I initialized a cue module and created a directory at root with a sub directory:
```
test/
├─ infrastructure/
│  ├─ prometheus/
│  │  ├─ ns.cue
```
ns.cue can be empty. I cd into test and ran `cue eval infrastructure/prometheus`.

### What did you expect to see?
An empty output or descriptive error.

### What did you see instead?
```
✦ ❯ cue eval infrastructure/prometheus
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0002c9e78)
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:328 +0x76
panic({0xe035c0?, 0xc0001be258?})
	runtime/panic.go:770 +0x132
cuelang.org/go/cue/load.(*loader).absDirFromImportPath(0xc0001c2980, {0x0?, 0x3?}, {0x7ffc0ecaf206, 0x19})
	cuelang.org/go@v0.8.0/cue/load/import.go:376 +0x130f
cuelang.org/go/cue/load.(*loader).newInstance(0xc0001c2980, {0x0?, 0xe60896?}, {0x7ffc0ecaf206, 0x19})
	cuelang.org/go@v0.8.0/cue/load/import.go:313 +0x37
cuelang.org/go/cue/load.(*loader).importPathsQuiet(0xc0001c2980, {0xc00041df20?, 0xc0002c9240?, 0x411e85?})
	cuelang.org/go@v0.8.0/cue/load/search.go:262 +0x599
cuelang.org/go/cue/load.(*loader).importPaths(0xc0002c95d0?, {0xc00041df20?, 0xc0004706c0?, 0xc00041df20?})
	cuelang.org/go@v0.8.0/cue/load/search.go:220 +0x27
cuelang.org/go/cue/load.Instances({0xc00041df20, 0x1, 0x1}, 0x517e01?)
	cuelang.org/go@v0.8.0/cue/load/instances.go:93 +0x4be
cuelang.org/go/cmd/cue/cmd.loadFromArgs(...)
	cuelang.org/go@v0.8.0/cmd/cue/cmd/common.go:115
cuelang.org/go/cmd/cue/cmd.parseArgs(0xc00046e3c0, {0xc00041df20, 0x1, 0x1}, 0xc00039fea0)
	cuelang.org/go@v0.8.0/cmd/cue/cmd/common.go:541 +0xa5
cuelang.org/go/cmd/cue/cmd.runEval(0xc00046e3c0, {0xc00041df20, 0x1, 0x1})
	cuelang.org/go@v0.8.0/cmd/cue/cmd/eval.go:88 +0x94
cuelang.org/go/cmd/cue/cmd.newEvalCmd.mkRunE.func1(0xc000461d00?, {0xc00041df20, 0x1, 0x1})
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:96 +0xc4
github.com/spf13/cobra.(*Command).execute(0xc000476008, {0xc00041dee0, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ed508)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00046e3c0, {0x16450a0?, 0xd74140?})
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:313 +0x65
cuelang.org/go/cmd/cue/cmd.Main()
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:241 +0xa5
main.main()
	cuelang.org/go@v0.8.0/cmd/cue/main.go:24 +0x13
```

**Comment by mvdan** [comment] 2024-03-26 06:44
Duplicate of https://github.com/cue-lang/cue/issues/2964 - fixed in master.

**Closed as not planned by mvdan** 2024-03-26 06:44 UTC
Labels: NeedsInvestigation, Triage
