### ISSUE TITLE
invalid memory address or nil pointer dereference in processComprehension on export

### ISSUE THREAD

**Issue by yujunz** [cue-lang/cue#2647] opened 2023-10-17 06:50 UTC
### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.6.0

go version go1.20.7
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```
cue export
```

### What did you expect to see?

Export content

### What did you see instead?
```
make
cue export pg.cue ../pg.cue ../../pg.cue ../../../pg.cue --force --outfile main.tf.json
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10080fa90]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x140002ddea0)
	cuelang.org/go/cmd/cue/cmd/root.go:318 +0x94
panic({0x100ecbc60, 0x101489420})
	runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/adt.(*nodeContext).processComprehension(0x14000b47000, 0x140003f8b40, 0x1?)
	cuelang.org/go/internal/core/adt/comprehension.go:400 +0x150
cuelang.org/go/internal/core/adt.(*nodeContext).injectComprehensions(0x14000b47000, 0x0?)
	cuelang.org/go/internal/core/adt/comprehension.go:332 +0x7c
cuelang.org/go/internal/core/adt.(*nodeContext).expandOne(0x14000b47000, 0x60?)
	cuelang.org/go/internal/core/adt/eval.go:2077 +0x70
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x14000ae3e00, 0x14000b366c0, 0x5)
	cuelang.org/go/internal/core/adt/eval.go:265 +0x5b8
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0x14000b38400, 0x5)
	cuelang.org/go/internal/core/adt/eval.go:794 +0x19c
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x14000b38400, 0xa4?)
	cuelang.org/go/internal/core/adt/eval.go:581 +0x4c4
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x14000b38400, 0x1?, 0x14000b38400, 0x0, 0x0, 0x1)
	cuelang.org/go/internal/core/adt/disjunct.go:158 +0x340
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x14000ae3e00, 0x14000b362d0, 0x5)
	cuelang.org/go/internal/core/adt/eval.go:292 +0x734
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0x14000b38000, 0x5)
	cuelang.org/go/internal/core/adt/eval.go:794 +0x19c
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x14000b38000, 0x0?)
	cuelang.org/go/internal/core/adt/eval.go:581 +0x4c4
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x14000b38000, 0x0?, 0x14000b38000, 0x0, 0x0, 0x1)
	cuelang.org/go/internal/core/adt/disjunct.go:158 +0x340
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x14000ae3e00, 0x14000b1fcb0, 0x5)
	cuelang.org/go/internal/core/adt/eval.go:292 +0x734
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0x1400054dc00, 0x5)
	cuelang.org/go/internal/core/adt/eval.go:794 +0x19c
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x1400054dc00, 0x40?)
	cuelang.org/go/internal/core/adt/eval.go:581 +0x4c4
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x1400054dc00, 0xa0?, 0x1400054dc00, 0x0, 0x0, 0x1)
	cuelang.org/go/internal/core/adt/disjunct.go:158 +0x340
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x14000ae3e00, 0x14000b0dd40, 0x5)
	cuelang.org/go/internal/core/adt/eval.go:292 +0x734
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
	cuelang.org/go/internal/core/adt/composite.go:638
cuelang.org/go/cue.newVertexRoot(0x14000ae3e00?, 0x14000ae3e00?, 0xf8?)
	cuelang.org/go/cue/types.go:614 +0x78
cuelang.org/go/cue.newValueRoot(0x100faa498?, 0x14000376e70?, {0x100fa8f00?, 0x14000b0dd40?})
	cuelang.org/go/cue/types.go:623 +0x3c
cuelang.org/go/cue.(*Context).make(0x14000376e70, 0x0?)
	cuelang.org/go/cue/context.go:253 +0x64
cuelang.org/go/cue.(*Context).BuildInstances(0x14000376e70, {0x140002dd8d8, 0x1, 0x1e0?})
	cuelang.org/go/cue/context.go:152 +0x1c0
cuelang.org/go/cmd/cue/cmd.buildInstances(0x14000397d10, {0x140002dd8d8, 0x1, 0x18?}, 0x1)
	cuelang.org/go/cmd/cue/cmd/common.go:729 +0x38
cuelang.org/go/cmd/cue/cmd.parseArgs(0x14000397d10, {0x1400037b6c0, 0x4, 0x7}, 0x14000389090)
	cuelang.org/go/cmd/cue/cmd/common.go:621 +0xb7c
cuelang.org/go/cmd/cue/cmd.runExport(0x14000397d10?, {0x1400037b6c0, 0x4, 0x7})
	cuelang.org/go/cmd/cue/cmd/export.go:106 +0x6c
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x140003d4600?, {0x1400037b6c0, 0x4, 0x7})
	cuelang.org/go/cmd/cue/cmd/root.go:87 +0x90
github.com/spf13/cobra.(*Command).execute(0x140003d4600, {0x1400037b650, 0x7, 0x7})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000033500)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x14000397d10, {0x8?, 0x8?})
	cuelang.org/go/cmd/cue/cmd/root.go:303 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
	cuelang.org/go/cmd/cue/cmd/root.go:231 +0x74
main.main()
	cuelang.org/go/cmd/cue/main.go:24 +0x1c
make: *** [main.tf.json] Error 2
```

**Comment by mvdan** [comment] 2023-11-13 15:12
I believe this is a duplicate of https://github.com/cue-lang/cue/issues/2550; the panic stack trace is almost identical.

If you update to CUE master, the panic should be fixed. The fix will be included in the next release.

**Closed as not planned by mvdan** 2023-11-13 15:12 UTC
Labels: NeedsInvestigation
