### ISSUE TITLE
Evaluation Error - "Element at Index 1 not allowed by earlier comprehension or reference cycle

### ISSUE THREAD

**Issue by Dadabhvai-Kashyap** [cue-lang/cue#2694] opened 2023-11-16 15:20 UTC
**Description:**
When using the `cue` tool for evaluation with the provided code, a discrepancy in behavior between versions `0.4.0-alpha.1` and `0.6.0` has been observed. The following code snippet is causing an issue during evaluation:

```cue
vars: [{name: "name1", value: "value1"},...]
env: [{name: "name2", value:"value2"},...]

env: env + vars
```

When evaluated using `cue eval code.cue --out=yaml` with version `0.4.0-alpha.1`, the output generated is as expected:

```yaml
vars:
- name: name1
  value: value1
env:
- name: name2
  value: value2
- name: name1
  value: value1
```

However, when the same code is evaluated using version `0.5.0` and current `0.6.0`, it returns an error:

```
env: element at index 1 not allowed by earlier comprehension or reference cycle
```

**Steps to Reproduce:**
1. Use the provided code snippet in a `.cue` file.
2. Run the command `cue eval code.cue --out=yaml` with `0.4.0-alpha.1` version.
3. Run the command `cue eval code.cue --out=yaml` with `0.6.0` version.
4. Observe the error message in latest version

**Expected Behavior:**  
The evaluation of the given code used to generate a YAML output similar to the one produced by version `0.4.0-alpha.1`, without encountering the "element at index 1 not allowed by earlier comprehension or reference cycle" error in version `0.6.0`.

I am not sure whether this is a bug or not and I suppose that the observed discrepancy might be related to recent changes in the cycle detection algorithm introduced in `0.5.0`,

**Possible solution:**
How do I achieve the same behavior in the latest version?

**Comment by mvdan** [comment] 2023-11-16 21:58
This is effectively a duplicate of https://github.com/cue-lang/cue/issues/2615.

`env: env + vars` is cyclic; unless `vars` is an empty list, you're essentially recursing forever.

You can avoid this by declaring a new list instead of extending or "appending to" an existing declared list: https://tip.cuelang.org/play/?id=_wIWn0NS5Ze#cue@export@cue

**Closed as not planned by mvdan** 2023-11-16 21:58 UTC
Labels: Triage
