### ISSUE TITLE
internal/eval: embedded scalar inconsistency

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1474] opened 2022-01-16 06:04 UTC
Uncovered by @mpvl whilst investigating comprehension changes in the https://review.gerrithub.io/c/cue-lang/cue/+/529524/10 stack.

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +1374dc99 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval x.cue

-- x.cue --
a: {
	2
	{
		#x: 1
	}
}

a: {
	#x: 1
	if true {
		2
	}
}
```

### What did you expect to see?

The above to pass.

### What did you see instead?

The above fails. It currently needs to be "fixed" by:

```
exec cue eval x.cue

-- x.cue --
a: {
	2
	{
		_
		#x: 1
	}
}

a: {
	#x: 1
	if true {
		2
	}
}
```

From a symmetry argument, however, this should work.

**Comment by mpvl** [comment] 2022-01-17 08:56
Duplicate of #1472. :)

**Closed as completed by mpvl** 2022-01-17 08:56 UTC
Labels: NeedsInvestigation

**Comment by myitcv** [comment] 2022-01-17 09:24
Ha!
