### ISSUE TITLE
Default value not resolved in strings.Join

### ISSUE THREAD

**Issue by eonpatapon** [cue-lang/cue#1357] opened 2021-11-03 16:47 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
exec cue export in.cue
cmp stdout stdout.golden
-- in.cue --
import "strings"

a: *"foo" | string
b: strings.Join([a], ",")
-- stdout.golden --
a: "foo"
b: "foo"

```

```
 ~/go/bin/testscript bug.txtar

> exec cue export in.cue
[stderr]
b: non-concrete value *"foo" | string for element 0 of string list argument 0:
    ./in.cue:4:4
    ./in.cue:4:18
[exit status 1]
```

**Comment by myitcv** [comment] 2021-11-06 08:58
Dupe of https://github.com/cue-lang/cue/issues/1025

**Closed as completed by myitcv** 2021-11-06 08:58 UTC
