### ISSUE TITLE
cue/fmt: a `let` assignment on the first line of a file gets indented with an extra space

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2459] opened 2023-06-26 09:11 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0-alpha.1

go version go1.20.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes, 0.5.0.

### What did you do?

txtar repro:

```
exec cp leading-let.cue before.txt
exec cue fmt leading-let.cue
cmp leading-let.cue before.txt
-- leading-let.cue --
let foo = 1
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
$ testscript leading-let.txtar 
> exec cp leading-let.cue before.txt
> exec cue fmt leading-let.cue
> cmp leading-let.cue before.txt
--- leading-let.cue
+++ before.txt
@@ -1,1 +0,0 @@
- let foo = 1
@@ -0,0 +1,1 @@
+let foo = 1

FAIL: /tmp/testscript3449709270/leading-let.txtar/script.txtar:3: leading-let.cue and before.txt differ
error running leading-let.txtar in /tmp/testscript3449709270/leading-let.txtar
```

**Comment by mvdan** [comment] 2023-06-26 12:50
This appears to be a duplicate of https://github.com/cue-lang/cue/issues/1544 :) I started a fix a while back, I'll look at reviving it.

**Closed as not planned by mvdan** 2023-06-26 12:50 UTC
Labels: NeedsInvestigation

**Comment by jpluscplusm** [comment] 2023-06-26 14:33
@mvdan apologies for the dupe! I did search (for issues matching "let fmt") but without any luck :-)

**Comment by mvdan** [comment] 2023-06-26 14:38
No worries! GitHub's search is notoriously bad with keywords :) I personally use `site:github.com/xxx/yyy/issues keywords` queries on Google all the time for this reason. Unfortunately, see https://github.com/cue-lang/cue/issues/1900.
