### ISSUE TITLE
Getting stuck with cycle reference in the import statement

### ISSUE THREAD

**Issue by selmison** [cue-lang/cue#1864] opened 2022-08-21 18:48 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
When a cue file in a module has a `import` statement referring to its own package, the `cue` command get stuck and don't return a error. E. g.:

#### Content of the `\<root dir\>/cue.mod/module.cue` file:
```cue
module: "<url>/<path>"
```

#### Content of the `\<root dir\>/test.cue` file:
```cue
package <package>

import (
	"<url>/<path>/<package>"
)
```

### What did you expect to see?
Return a error message informing a cycle reference in the import statement.

### What did you see instead?
Cue command get stuck

**Comment by mvdan** [comment] 2023-05-10 15:43
Thanks for filing this bug! It appears to be a duplicate of https://github.com/cue-lang/cue/issues/849; closing for now.

**Closed as not planned by mvdan** 2023-05-10 15:43 UTC
Labels: NeedsInvestigation
