### ISSUE TITLE
use cue to vet another cue file

### ISSUE THREAD

**Issue by sahroshan** [cue-lang/cue#2210] opened 2023-01-11 12:00 UTC
Hi,
I am trying to validate a cue file with another cue file. Is it possible to validate cue with another cue?

### What version of CUE are you using (`cue version`)?

<pre>
➜  cue version
cue version v0.5.0-beta.2

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1

</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?
1. create a schema file
```
-- schema.cue
close({
	foo: bar: string
})
```

2. create another cue file
```
-- another.cue
foo: {
	bar: "passed down"
}
extra: "this extra field not defined in schema"
```

4. run vet command `cue vet another.cue schema.cue`

### What did you expect to see?

Error for field `extra` in another.cue

### What did you see instead?

`cue vet another.cue schema.cue` does not raise any error. And exit status is 0.

**Comment by mvdan** [comment] 2023-06-14 11:52
Duplicate of https://github.com/cue-lang/cue/issues/2214, which was converted from your discussion with the same request.

**Closed as not planned by mvdan** 2023-06-14 11:52 UTC
Labels: NeedsInvestigation, Triage
