### ISSUE TITLE
modules: dependency modules that have a gen directory can't be used

### ISSUE THREAD

**Issue by vikstrous2** [cue-lang/cue#3233] opened 2024-06-14 14:48 UTC
### What version of CUE are you using (`cue version`)?

<pre>
cue version v0.9.0-rc.1

go version go1.22.1
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.9.0
</pre>

### Does this issue reproduce with the latest stable release?
yes

### What did you do?
In a new directory, create a module and add a dependency:
```
cue mod init github.com/vikstrous/cuek8stest
cue mod get github.com/vikstrous/cuek8s
```
Create a file: `test.cue`
```
package cuek8stest

import "github.com/vikstrous/cuek8s"

hello: cuek8s.#Hello

service: cuek8s.#Service
```

Then run `cue eval`

### What did you expect to see?
it shouldn't error

### What did you see instead?
```
github.com/vikstrous/cuek8stest@v0.github.com/vikstrous/cuek8s: import failed: import failed: cannot find package "k8s.io/api/core/v1": cannot find module providing package k8s.io/api/core/v1:
    ./test.cue:3:8
    ../.cache/cue/mod/extract/github.com/vikstrous/cuek8s@v0.0.9/hello.cue:3:8
```

**Comment by nyarly** [comment] 2024-06-18 00:58
I'm seeing something similar as well

**Comment by ckazimie** [comment] 2024-06-23 13:57
Same here.

**Comment by vikstrous2** [comment] 2024-06-24 13:02
I'm planning to start trying to work around this by rewriting package paths and moving the gen packages out of the gen directory. To reproduce this issue, use version v0.0.8 of https://github.com/vikstrous/cuek8s

**Comment by vikstrous2** [comment] 2024-06-24 14:01
This is the workaround: https://github.com/vikstrous/cuek8s/blob/master/generate.sh

**Comment by tvandinther** [comment] 2024-07-02 09:16
I am also encountering this issue with a module published using `0.9.2` and `source: kind: "self"`.

**Comment by rogpeppe** [comment] 2024-07-18 13:16
Note that this behaviour is documented in the introduction to the [CUE modules reference](https://cuelang.org/docs/reference/modules):
> as a transitionary measure, the CUE tool still supports the import of packages present in the `cue.mod/pkg`, `cue.mod/usr` and `cue.mod/gen` directories. This only applies to the main module, and if there is any ambiguity with respect to regular module dependencies an “ambiguous import” error will be reported.

Note the "as a transitionary measure" caveat above. Eventually, it's possible/probable that support for the `gen`, `usr` and `pkg` directories will be dropped in favour of regular published packages.

**Comment by rogpeppe** [comment] 2024-07-18 13:25
Closing this issue as everything seems to be functioning as intended.

**Closed as not planned by rogpeppe** 2024-07-18 13:25 UTC
Labels: NeedsInvestigation
