### ISSUE TITLE
cmd/cue: -l flag cannot combine context (filename) and expression on input data

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2124] opened 2022-11-23 08:20 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221119112418-32bfffd0aa53

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 32bfffd0aa538d63757efeef393bc37a06c8c9a4
        vcs.time 2022-11-19T11:24:18Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
# Use the detail field to construct a path for the imported result
exec cue import -l detail -o - input.json
cmp stdout no_context.golden

# Use the filename to construct a path for the imported result
exec cue import --with-context -l 'path.Base(filename, path.Unix)' -o - input.json
cmp stdout context.golden

# Can I combine the two?
exec cue import --with-context -l 'path.Base(filename, path.Unix)' -l detail -o - input.json
cmp stdout combined.golden

-- input.json --
{
	"filename": "rubbish",
	"detail": "something"
}
-- no_context.golden --
something: {
	filename: "rubbish"
	detail:   "something"
}
-- context.golden --
"input.json": {
	filename: "rubbish"
	detail:   "something"
}
-- combined.golden --
"input.json": something: {
	filename: "rubbish"
	detail:   "something"
}
```

### What did you expect to see?

A passing test. 

### What did you see instead?

It's not possible to provide a `-l` path that combines references to both context information (`filename` et al) and expressions that refer to the object being imported:

```
$ ts repro.txtar
# Use the detail field to construct a path for the imported result (0.017s)
# Use the filename to construct a path for the imported result (0.016s)
# Can I combine the two? (0.014s)
> exec cue import --with-context -l 'path.Base(filename, path.Unix)' -l detail -o - input.json
[stderr]
error evaluating label detail: reference "detail" not found
[exit status 1]
FAIL: /tmp/testscript991473742/repro.txtar/script.txtar:10: unexpected command failure
```

That said, the expectation above needs to be caveated. `--with-context` provides an undocumented means to address contextual information which, as demonstrated in the second case, includes `filename`. In the third example above, `filename` is an ambiguous reference to either the filename provided by `--with-context` or the field by the same name for the object being imported. It's unclear therefore that we can combine references to both context information (`filename` et al) and expressions that refer to the object being imported; in the general case it will be ambiguous. We might need to think about a different way of referencing context information (`#context`?).

Also, the data provided by `--with-context` does not appear to be documented.

**Comment by rogpeppe** [comment] 2022-11-23 09:27
The data provided by `--with-context` is documented in `cue help flags`.
Admittedly that could/should be referred to elsewhere in the docs (I always forget where it lives myself!).

Those docs show that the original data is available in the `data` field, so your example can be made to work
by using this incantation:

```
exec cue import --with-context -l 'path.Base(filename, path.Unix)' -l data.detail -o - input.json
```

So I'll close this issue as "working as intended" and raise another to improve the docs for `--with-context`
which are clearly not surfaced as clearly as they should be.

**Closed as completed by rogpeppe** 2022-11-23 09:27 UTC
Labels: WorkingAsIntended

**Comment by myitcv** [comment] 2022-11-23 09:34
Ah perfect, thanks!
