### ISSUE TITLE
Git Branch Rename: "master" --> "main"

### ISSUE THREAD

**Issue by halcyondude** [cue-lang/cue#1875] opened 2022-08-23 22:19 UTC
### What version of CUE are you using (`cue version`)?

cue version v0.4.3 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I'm new here and plan to use cue for a new OSS project. I'm excited!

I noticed that the cue's main branch is 'master' and didn't see an issue to `s/master/main`

### What did you expect to see?

main

### What did you see instead?

master

**Comment by verdverm** [comment] 2022-08-24 05:10
Why are you expecting `main` as the default branch name?

For some historical context, CUE was a fork of Go circa 2018 iirc. Go uses the same `master` as the primary branch (https://github.com/golang/go)

Also note, the GitHub repo is primarily a mirror from Gerrit, though I believe the maintainers use https://github.com/cue-sh/copybara to provide a two way sync or maybe https://github.com/cue-lang/cue/tree/master/internal/ci

https://review.gerrithub.io/q/project:cue-lang%252Fcue

**Comment by myitcv** [comment] 2022-08-24 13:32
Thanks, @halcyondude. https://github.com/cue-lang/cue/issues/1092 is the issue for this one. So I'll close this issue as a duplicate of that one.

We will very likely make this change as part of a wider repository reorganisation. 

As @verdverm pointed out, when CUE landed in [its new home](https://github.com/cue-lang/cue/issues/1078), we switched to using GerritHub as the Gerrit code review host. It has native replication to GitHub (via a plugin). Switching from `master` to `main` should therefore be trivial, indeed the wonderful folks at GerritHub folks (hi @lucamilanesio!) have confirmed as much.

**Closed as completed by myitcv** 2022-08-24 13:32 UTC
Labels: NeedsInvestigation
