### ISSUE TITLE
builtin: expose fmt.Sprint* as builtins

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2485] opened 2023-07-12 06:44 UTC
**Is your feature request related to a problem? Please describe.**

In order to leverage `fmt`-like behaviour, we currently have to drop down to the `text/template` package:

```cue
import "text/template"

i: 10
res: template.Execute(#"{{printf "%04d" . }}"#, i)
```

Playground: https://tip.cuelang.org/play/?id=STXBegHgGPs#cue@export@cue

**Describe the solution you'd like**

To be able to use a `fmt`-like builtin:

```cue
import "fmt"

i: 10
res: fmt.Sprintf("%04d", i)
```

**Describe alternatives you've considered**

As above, working around with `text/template`, or defining the `fmt`-like behaviour manually via `strings` and friends.

**Additional context**

n/a

cc @seh @verdverm

**Comment by mvdan** [comment] 2024-05-21 09:13
This is a duplicate of https://github.com/cue-lang/cue/issues/1463, I'm pretty sure :) There are more thumbs up reactions in this issue, but the other has input from Marcel and is older, so I think the other is the one to keep around.

**Closed as not planned by mvdan** 2024-05-21 09:13 UTC
Labels: FeatureRequest

**Comment by myitcv** [comment] 2024-05-23 14:07
Goodness me. That memory of mine again... and I created the issue!
