### ISSUE TITLE
Allow cue fmt to report when files have been/will be formatted

### ISSUE THREAD

**Issue by eonpatapon** [cue-lang/cue#2172] opened 2022-12-06 10:31 UTC
**Is your feature request related to a problem? Please describe.**

To ensure all cue files are properly formatted it's common to have a check in a CI pipeline.

Currently to check formatting I have to run `cue fmt` then check with `git` if some files have been modified (which is not trivial).

It would be nice if `cue fmt` can report somehow if files have been or will be formatted.

**Describe the solution you'd like**

Here's some ideas:
- an option that list the files that would be formatted (like `gofmt -l`)
- an option that returns a non-zero exit code when files have been formatted

**Comment by seh** [comment] 2022-12-06 20:45
See #363 for previous coverage.

**Comment by mvdan** [comment] 2022-12-06 21:56
Yes, this seems like a duplicate of #363 - or at least very much related. I'm going to close as a duplicate, for the sake of not duplicating the discussion.

**Closed as not planned by mvdan** 2022-12-06 21:56 UTC
Labels: FeatureRequest
