### ISSUE TITLE
evaluator: regression in variable substitution behavior on 0.5.0-alpha.1

### ISSUE THREAD

**Issue by hzuo** [cue-lang/cue#2041] opened 2022-10-24 21:14 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-alpha.1

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I have this snippet in my Cue config file:

```cue
for k, container_dst in service.runtime_dep_volumes {
	let dev_fs_path = dev_fs_layout[service.name].docker_dev_runtime_deps[k]

	_check: true & !strings.HasPrefix(dev_fs_path, ".")

	"./\(dev_fs_path):\(container_dst)"
},
```

### What did you expect to see?

This worked fine on 0.4.3, but not on v0.5.0-alpha.1 - it fails with:
```
docker_compose_template.services."acme-server".volumes.0._check: invalid selector dev_fs_path for value of type string:
    ./blueprint.cue:1997:42
```

### What did you see instead?

If you inline the definition of `dev_fs_path` into the `strings.HasPrefix` call, it will continue to work, i.e.:

```cue
for k, container_dst in service.runtime_dep_volumes {
	let dev_fs_path = dev_fs_layout[service.name].docker_dev_runtime_deps[k]

	_check: true & !strings.HasPrefix(dev_fs_layout[service.name].docker_dev_runtime_deps[k], ".")

	"./\(dev_fs_path):\(container_dst)"
},
```

But clearly simply using the variable `dev_fs_path` should work here.

**Comment by myitcv** [comment] 2022-10-25 02:05
Thanks for raising this. Unfortunately I can't reproduce this using your CUE above. 

Please can you share a complete reproduction of the problem?

If this is private code, please feel free to DM me on Slack (`myitcv`) or via email (`paul at cue.works`).

**Comment by mvdan** [comment] 2023-01-18 23:13
@hzuo did you see @myitcv's response above? You can DM me on Slack at "mvdan" as well, or email me at the same username at cue.works.

You should also try the latest master version, as we have fixed a number of regressions recently.

**Comment by mvdan** [comment] 2023-04-05 17:49
Closing this for now, as we still aren't able to reproduce. More than happy to reopen if you can provide more details.

**Closed as not planned by mvdan** 2023-04-05 17:49 UTC
Labels: CannotReproduce, NeedsInvestigation
