### ISSUE TITLE
`cue get go` panics when extracting definition from `envoyproxy/go-control-plane`

### ISSUE THREAD

**Issue by unicell** [cue-lang/cue#1097] opened 2021-07-13 23:29 UTC
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, with 0.4.0 release. Didn't try cue source build.

### What did you do?

Steps to reproduce
```
# start within an empty directory
go mod init "example.com"
go get github.com/envoyproxy/go-control-plane/...@v0.9.9

cue mod init example.com
cue get go github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3
```

### What did you expect to see?

CUE definition generated as demonstrated with k8s api types[1]

[1] https://cuelang.org/docs/integrations/go/#extract-cue-from-go

### What did you see instead?

```
$  cue get go github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1766340]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0017edec0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0x181f6a0, 0x1e2c780)
        /opt/hostedtoolcache/go/1.15.12/x64/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc007ab63f0, 0xc00003a0f4, 0x26, 0x0, 0x1e84ca0, 0x3e)
        /home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:453 +0x60
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc007ab63f0, 0xc00003a0f4, 0x26, 0xc0065e3320, 0xc004cbfb68, 0x1)
        /home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:569 +0x1355
cuelang.org/go/cmd/cue/cmd.extract(0xc0003ac220, 0xc000345810, 0x1, 0x1, 0x11fce60, 0xc000323c88)
        /home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:432 +0x65c
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003c0b00, 0xc000345810, 0x1, 0x1, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0003c0b00, 0xc0003457e0, 0x1, 0x1, 0xc0003c0b00, 0xc0003457e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c7080, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0003ac220, 0x19f5b00, 0xc000124008, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0x19f5b00, 0xc000124008, 0xc000122050, 0x3, 0x3, 0x192fd70, 0xc000323f48)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc00010c058)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /home/runner/work/cue/cue/cmd/cue/main.go:24 +0x25
```

```
$  tree cue.mod/
cue.mod/
├── gen
│   └── github.com
│       └── envoyproxy
│           └── go-control-plane
│               └── envoy
│                   └── config
│                       └── cluster
│                           └── v3
│                               ├── circuit_breaker.pb_go_gen.cue
│                               ├── cluster.pb_go_gen.cue
│                               ├── filter.pb_go_gen.cue
│                               └── outlier_detection.pb_go_gen.cue
├── module.cue
├── pkg
└── usr

10 directories, 5 files
```

**Comment by myitcv** [comment] 2021-07-15 11:53
Thanks for the report, @unicell. This is a duplicate of #621 which I'm going to look to fix sooner rather than later, now that the migration (#1078) is complete. Closing this therefore.

**Closed as completed by myitcv** 2021-07-15 11:53 UTC
Labels: NeedsInvestigation
