### ISSUE TITLE
doc/contribute.md: wrong `git codereview` parameter

### ISSUE THREAD

**Issue by palmamartin** [cue-lang/cue#1403] opened 2021-11-25 19:43 UTC
I think at [Step 5: Revise changes after a review](https://github.com/cue-lang/cue/blob/master/doc/contribute.md#step-5-revise-changes-after-a-review) the `-s` parameter should be omitted. Otherwise the `Signed-off-by: ...` line will be duplicated in the commit message.

**Comment by rogpeppe** [comment] 2022-04-14 11:52
@palmamartin Thanks for the report, but I just checked, and the `Signed-off-by` line isn't duplicated if it's already present, so ISTM that the instructions are actually correct, so I'm closing this as working as intended. Please reopen the issue if you think that's the wrong thing to do.

**Closed as completed by rogpeppe** 2022-04-14 11:52 UTC
Labels: WorkingAsIntended

**Comment by mpvl** [comment] 2022-05-17 11:35
I used to have the same problem. The problem was a bug in git codereview. Updating to a newer version fixed it.
